package eu.kastroguru.astrodiary.domain.humandesign

/**
 * Human Design descriptive text content.
 * Each value is a Pair<String, String> — (English, Bulgarian).
 */
object HdDescriptions {

    // ── Types ─────────────────────────────────────────────────────────────────
    data class TypeInfo(
        val name: Pair<String, String>,
        val percent: String,
        val aura: Pair<String, String>,
        val description: Pair<String, String>,
        val strategy: Pair<String, String>,
        val signature: Pair<String, String>,
        val notSelf: Pair<String, String>
    )

    val typeInfo: Map<HdType, TypeInfo> = mapOf(
        HdType.GENERATOR to TypeInfo(
            name = "Generator" to "Генератор",
            percent = "~36%",
            aura = "Open & Enveloping" to "Отворена и обгръщаща",
            description = ("Generators are often the workforce of the collective, with a defined Sacral center that produces reliable energy for work, creativity, and relationships. Their sacral response can naturally attract opportunities when they wait to respond rather than force outcomes. Generators benefit from following what genuinely excites them, honoring rest cycles, and setting boundaries so their sustaining energy isn’t depleted by obligation or pressure.")
                    to ("Генераторите често са двигателите на ежедневието — притежават дефиниран Сакрален център, който произвежда устойчива енергия за работа, творчество и връзки. Тази сакрална сила може да бъде магнит за възможности, когато е използвана интуитивно чрез отговор, а не чрез постоянна инициатива. За генераторите е полезно да следват това, което истински ги вълнува, да почиват ритмично и да поставят граници, за да запазят устойчивостта си."),
            strategy = "Wait to respond. Life often presents people, events, or information that invite a genuine sacral reaction — a brief gut sound or sensation like an effortless “ah‑huh” (yes) or a low “uh‑uh” (no). Practice pausing and noticing rather than initiating from the mind alone: this conserves energy, avoids unnecessary commitments, and helps you choose what truly energizes you. If impatience arises, remind yourself that waiting for what resonates usually leads to clearer, more sustainable choices."
                    to "Изчакай и откликни. Животът често поставя пред теб хора, събития или възможности, които провокират истинска сакрална реакция — кратък вътрешен или вербален импулс като спонтанно „ах-ха“ (да) или тихо „ъм-ъм“ (не). Практикувай пауза и наблюдение вместо да инициираш само от ума: това помага да пестиш енергия, да избягваш ненужни задължения и да избереш дейности, които наистина те зареждат. Когато усещаш нетърпение, припомни си, че изчакването често води до по-ясни и устойчиви избори.",
            signature = "Satisfaction" to "Удовлетворение",
            notSelf = "Frustration often shows up when you initiate instead of responding, or when the work fails to elicit a clear sacral “yes.” It can feel like stagnation, irritation, or a muted dissatisfaction. When you notice this tone, pause and check for the sacral signal; realign with activities that energize you. Small experiments, timely rest, and shifting toward what consistently lights you up can reduce frustration and help restore flow."
                    to "Разочарование често се появява, когато човек инициира вместо да откликне, или когато задачата не провокира сакралното „да“. Може да се усети като вътрешно напрежение, скука или усещане за застой. Когато забележиш този тон, спри и провери сакралния си отговор; пренасочи усилията към дейности, които те зареждат. Експериментирай с различни подходи, прави паузи за възстановяване и давай приоритет на това, което наистина работи за теб, за да намалиш разочарованието."
        ),
        HdType.MANIFESTING_GENERATOR to TypeInfo(
            name = "Manifesting Generator" to "Манифестиращ генератор",
            percent = "~32%",
            aura = "The aura is open and enveloping, naturally drawing people and opportunities into your orbit. This quality can facilitate rapid collaboration and influence, but it can also blur boundaries and lead to overcommitment. Practice clear informing, monitor your sacral responses, and protect recovery time. Those habits help you stay engaged without burning out, allowing you to both welcome others and preserve your energy." to "Аурата е отворена и обгръщаща — често привличаш хора и възможности с топлина и присъствие. Това улеснява бързото влияние и колаборация, но може и да размива границите, така че да поемаш повече, отколкото е устойчиво. Практикувай ясно информиране и слушай сакралните си реакции; отделяй време за възстановяване и поставяй граници, когато е нужно, за да запазиш баланс между ангажираност и почивка.",
            description = ("Manifesting Generators combine sustained sacral energy with a direct motor‑to‑Throat connection, which often enables swift action and visible expression. They tend to be passionate about multiple projects, adept at multitasking, and capable of accelerating or shortcutting processes. Skipping steps can speed progress but may require later corrections. Practically, waiting to respond, following your sacral impulses, and informing others when you act reduces friction, supports sustainable output, and increases overall satisfaction.")
                    to ("Манифестиращите генератори са хибриден тип с изразена сакрална енергия и пряка мотор–гърло връзка, което често им дава възможност за бързо действие и ясно изразяване. Те са страстни към много различни теми, могат да мултитаскват и да ускоряват процеси, но понякога прескачат стъпки — това спестява време, но може да наложи корекции по-късно. Полезно е да чакат отклик преди да поемат големи ангажименти, да информират засегнатите и да отделят време за възстановяване, за да намалят съпротивлението и да увеличат удовлетворението."),
            strategy = "Wait to respond, then inform before you act. Once your sacral response signals “yes,” telling others your intention is a practical way to reduce resistance — it’s not asking for permission but creating clarity so cooperation can flow. Informing smooths social dynamics and prevents unnecessary pushback when you move. If you meet friction or feel rushed, return to the sacral check and consider whether more time or clearer communication is needed."
                    to "Изчакай и откликни; след като сакралният ти отговор е „да“, информирай хората, които ще бъдат засегнати, преди да предприемеш действие. Информирането не е искане за разрешение, а начин да намалиш съпротивлението, да създадеш яснота и да улесниш сътрудничеството. Тази практика помага да избегнеш недоразумения и ненужно противопоставяне. Ако усещаш напрежение или бързане, върни се към сакралната проверка и обмисли дали не е нужна още една пауза или по-ясна комуникация.",
            signature = "Satisfaction" to "Удовлетворение",
            notSelf = "Frustration and flashes of anger often arise when a Manifestor pushes things or acts without informing others. These emotions can indicate the natural flow of initiation is being interrupted and that the person meets resistance or confusion in their environment. Paying attention to when pressure makes you hurry and practising brief, clear notifications to affected people can reduce friction. That approach helps contain reactive feelings, maintain personal integrity, and create more constructive interactions without asking permission to initiate."
                    to "Чувство на разочарование и изблици на гняв често възникват, когато манифесторът се опитва да форсира нещата или действа без да информира други. Тези емоции могат да сигнализират, че е нарушен естествения им ритъм на инициатива и че срещат съпротива или неразбиране около себе си. Полезно е да наблюдавате кога натискът ви кара да бързате и да практикувате кратки, ясни известия към хората си — това намалява напрежението и позволява да запазите усещане за вътрешен баланс."
        ),
        HdType.MANIFESTOR to TypeInfo(
            name = "Manifestor" to "Манифестор",
            percent = "~8%",
            aura = "Closed and repelling" to "Закрита, отблъскваща",
            description = ("Manifestors have a natural capacity to initiate without waiting for external approval. They often have a motor linked to the Throat, which can give their presence a strong, catalytic quality and the ability to set events in motion. They’re designed to start things rather than seek permission, and that autonomy can unsettle others who feel pushed or unprepared. A constructive approach is to inform people in advance—not as a request for consent but to reduce resistance, invite practical support, and protect personal autonomy while maintaining relationships.")
                    to ("Манифесторите са сред типовете с вродена способност да инициират действия без да чакат външно съгласие. Често имат мотор, свързан пряко с Гърлото, което им дава силно въздействие и способност да предизвикват движение. Проектирани са да започват процеси и да прокарват път, не да искат разрешение; това може да предизвика напрежение у околните, които не разбират защо усещат отдръпване. Балансираща практика е да информирате предварително — не за да търсите одобрение, а за да намалите съпротивата и да увеличите подкрепата."),
            strategy = "Informing the people in your life before you act often reduces resistance and lets others adapt. This is not about asking permission but giving a brief heads‑up about who will be affected and what’s coming. Practically, it leads to fewer disruptions, fewer misunderstandings, and a greater chance of receiving support, while preserving your freedom to initiate and steer events."
                    to "Информирането на хората около вас преди да предприемете действие често намалява съпротивлението и позволява на другите да се адаптират. Това не означава да търсите разрешение, а да дадете кратък сигнал — кой ще бъде засегнат и какво предстои. Практическият ефект е по‑малко спънки, по‑малко недоразумения и по‑висока вероятност за подкрепа, като същевременно запазвате свободата да инициирате.",
            signature = "Peace" to "Мир",
            notSelf = "Bitterness and anger often surface when a Projector’s guidance goes unrecognized or when they’re pressured to initiate without an invitation. These emotions can point to feeling unseen or undervalued for their distinctive perspective and capacity to manage others’ energy. It can help to wait for invitations that acknowledge your skills, to avoid forcing initiatives, and to set clear boundaries around how and when you engage. Over time this reduces resentment and creates healthier, more reciprocal interactions."
                    to "Горчивина и гняв често се появяват, когато проектирането усилия не е признато или когато другите натискат човека да започне, без да го поканят. Тези чувства могат да сигнализират, че не сте били видени или оценени за своята уникална перспектива и умение да управлявате енергията на другите. Полезно е да търсите покани и признание, да ограничавате едностранните инициативи и да работите върху ясно поставяне на граници — това може да намали горчивината и да създаде по‑здрава обмяна."
        ),
        HdType.PROJECTOR to TypeInfo(
            name = "Projector" to "Проектор",
            percent = "~20%",
            aura = "Focused and absorbing" to "Фокусирана и поглъщаща",
            description = ("Projectors are designed to guide, manage, and organize the energy of others. Their aura is penetrating and focused, allowing them to perceive deeper patterns and potential in people and systems. They often operate as natural advisors, strategists, and leaders, but their influence tends to land best when it is recognized and invited. Offering guidance without an invitation can lead to resistance or disappointment. Practical strategies include building visible expertise, setting clear boundaries, and cultivating patience — these help the Projector’s insights be received and protect them from burnout.")
                    to ("Проекторите са проектирани да насочват, управляват и организират енергията на другите. Тяхната аура е проникваща и концентрирана, което им позволява да усещат дълбоко потенциала и динамиката в хората и системите около тях. Често са естествени съветници, стратези и ръководители, но тяхното влияние работи най-добре, когато е признато и поканено. Ако дават напътствия без покана, това може да предизвика съпротива или разочарование. Практически подходи включват развиване на видимост и експертиза, установяване на граници и търпение — така вашата мъдрост ще бъде приета по-лесно и ще ви предпази от изтощение."),
            strategy = "Wait for recognition and invitation before offering guidance or making major moves. An invitation functions as a natural filter: it provides context and increases the likelihood that your energy will be welcomed. While you wait, refine your skills, build a reputation, and prioritize recovery so you’re more effective when opportunities arise. Avoid forcing influence or trying to operate like energy types; clear boundaries and patience typically produce more constructive outcomes."
                    to "Изчакайте разпознаване и покана, преди да давате съвет или да предприемате големи стъпки. Поканата служи като естествен филтър: дава контекст и увеличава шансът вашата енергия да бъде приета. Докато чакате, усъвършенствайте уменията си, изграждайте репутация и се грижете за възстановяването си — така ще бъдете по-ефективни, когато поканата дойде. Избягвайте да налагате мнението си или да се конкурирате като енергиен тип; ясните граници и търпението обикновено водят до по-добри резултати.",
            signature = "Success" to "Успех",
            notSelf = "The Projector’s not-self theme is often described as bitterness. This can arise when offering unsolicited advice, when one’s gifts go unrecognized, or when trying to work like energy types and becoming overextended. Bitterness may show up as frustration, inner dissatisfaction, or withdrawal. Practical approaches include waiting for invitation, establishing boundaries, listening to bodily signals, and prioritizing rest — these practices help reduce accumulated resentment and restore clarity."
                    to "Темата на „не-себе-си“ за проекторите често се описва като горчивина. Тя може да се появи, когато давате нежелани съвети, когато вашите дарби остават непризнати или когато се опитвате да работите като енергиен тип и се претоварвате. Горчивината се проявява като разочарование, вътрешно недоволство или отчуждение. Практически съвети включват научаване да чакате покана, да поставяте граници, да обръщате внимание на сигналите на тялото и да отделяте време за възстановяване — това помага да се редуцира натрупаната горчивина."
        ),
        HdType.REFLECTOR to TypeInfo(
            name = "Reflector" to "Рефлектор",
            percent = "~1%",
            aura = "Stable & exploratory" to "Стабилна и изследваща",
            description = ("Reflectors have no defined centers and are highly open; they function like mirrors that reflect the health and tone of their environment back to the community. Because of this sensitivity, they are strongly influenced by those around them and by the lunar cycle — different phases can activate different parts of the chart, so days often feel very different. Reflectors can act as barometers of group dynamics but are vulnerable to overwhelm if the setting is unsupportive. It’s helpful to allow time—often a lunar cycle—before major decisions, to curate one’s community, and to prioritize environments that support recovery and clarity.")
                    to ("Рефлекторите нямат дефинирани центрове и са силно отворени; те действат като огледала, които отразяват здравето и настроението на средата към общността. Поради тази чувствителност те често са дълбоко повлияни от хората около себе си и от лунния цикъл — различните фази активират различни области в тяхната карта, така че дните могат да изглеждат коренно различни. Рефлекторите могат да служат като барометър за групова динамика, но също така са уязвими към изтощение, ако средата е неподходяща. Полезно е да си дадат време (често се препоръчва лунен цикъл) преди важни решения, да подбират внимателно общността си и да приоритизират условия, които подпомагат възстановяването им."),
            strategy = "Wait a full 28‑day lunar cycle before making major decisions. During that time, notice how your feelings and perspectives shift — choices made in different phases often reveal themselves differently later on. Talk with a variety of people to gather viewpoints, but treat those conversations as information‑gathering rather than a final verdict. Keep brief notes, run small experiments, and give your emotional wave time to move through. This approach helps you reach clearer, more durable choices instead of acting from a short‑term swing or pressure."
                    to "Изчакай пълен 28‑дневен лунен цикъл преди да взимате важни решения. През този период наблюдавай как се променят емоциите и гледните ти точки — решенията, взети в различни фази, често изглеждат по‑различно на по‑късен етап. Говори с различни хора, за да събереш перспективи, но третирай разговорите като събиране на информация, а не като принудителен финал. Води кратки записи, прави малки експерименти и давай време на емоционалната вълна да премине. Така можете да достигнеш до по‑ясно и устойчиво решение, вместо да действаш от моментен изблик.",
            signature = "Delight is a sign you’re in alignment. When activities, relationships, and choices bring ease, joy, and natural attraction, they often point in the right direction. Notice the small moments of pleasure and which pursuits give you energy — they can act as a practical compass for prioritizing and deciding when to say yes or no." to "Удоволствието е знак, че си в съзвучие със себе си. Когато дейностите, връзките и решенията ти носят лекота, радост и естествено привличане, това често насочва към правилна посока. Обърни внимание на тихите моменти на възторг и на това кои занимания ти дават енергия — те могат да служат като практичен компас при приоритизиране и избиране на ангажименти.",
            notSelf = "Disappointment often arises from rushed decisions or staying in environments that don’t fit your needs and energy. If you frequently feel drained, empty, or unfulfilled, check whether you’re acting under external pressure or sacrificing your priorities. Practice pauses, set clear boundaries, and allow moments of self‑reflection — these steps help you recognize patterns and move toward more sustainable choices."
                    to "Разочарованието често се появява, когато взимате прибързани решения или оставаш в среда, която не отразява твоите нужди и енергия. Ако често се чувствате изтощен, празен или неудовлетворен, провери дали действаш под външен натиск или жертваш собствените си приоритети. Практикувай паузи, поставяй ясни граници и отделяй време за самонаблюдение — това помага да разпознаеш моделите и да възстановиш по‑устойчив начин на избор."
        )
    )

    // ── Authorities ───────────────────────────────────────────────────────────
    val authorityInfo: Map<HdAuthority, Pair<String, String>> = mapOf(
        HdAuthority.EMOTIONAL to (
            "Your truth lives in the emotional wave and clarity comes with time. At an emotional high or low there is rarely a final answer — wait for the wave to pass before committing. Clarity can arrive in hours, days, or weeks. Let others know you need time, keep a short record of shifting feelings, and run small experiments to test choices. Avoid making irreversible decisions during emotional extremes; giving things space often leads to wiser, more grounded outcomes."
                    to "Твоята истина живее в емоционалната вълна и яснотата идва с времето. В момента на емоционален пик или спад няма окончателна истина — изчакай вълната да премине преди да се ангажираш. Ясността може да дойде след часове, дни или седмици. Уведоми хората около теб, че ще поискате време, води дневник на емоционалните промени и използвай малки експерименти, за да тестваш решенията си. Избягвай да взимате окончателни решения в емоционален екстремум; пространството често носи по‑мъдро разглеждане."
        ),
        HdAuthority.SACRAL to (
            "Your authority is the immediate sacral response — an audible uh‑huh for yes or a clear uhn‑un for no. The sacral speaks in the moment through vocal reactions, sounds, and bodily sensations around the gut. Trust that impulse without mental override. Practice with clear yes/no questions; notice the first sound or sensation and avoid rationalizing it away. Small experiments build confidence in this practical, body‑felt way of deciding."
                    to "Твоят авторитет е непосредственият сакрален отговор — звучно „ъ‑ъ‑ха“ за да или „ъ‑ъ‑не“ за не. Сакралният говори в момента чрез гласови реакции, звуци и физически усещания в коремната област. Доверявай се на този импулс без ментално претъкмяване. Практикувай с ясни въпроси, които изискват да/не отговор; наблюдавай първоначалния звук или усещане и избягвай рационализирането му. Малки експерименти подсилват увереността в този практичен, телесно‑осъзнат начин за вземане на решения."
        ),
        HdAuthority.SPLENIC to (
            "Splenic authority is the quiet, instantaneous voice of in‑the‑moment intuition. It whispers once and seldom repeats — you need to be present enough to catch that single signal. It’s tied to a sense of safety and well‑being and often appears as an immediate physical reaction: a release, a tightening, or a sudden sense that something is right or not. Cultivate presence and learn to trust your first, fleeting response in the moment."
                    to "Спленичният авторитет е тихият, мигновен глас на интуицията в настоящия момент. Той шепне само веднъж и рядко се повтаря — трябва да сте достатъчно присъстващ, за да уловиш този единствен сигнал. Свързан е с усещането за безопасност и здравословност и често се проявява като моментална физическа реакция: отпускане, напрежение или внезапно усещане за „това е правилно/не е правилно“. Практикувай присъствие и се научи да доверяваш първата си реакция на място."
        ),
        HdAuthority.EGO to (
            "Your authority is the Ego/Heart — decisions follow what your heart genuinely wants and what supports your will and interests. Practice by saying your choice aloud and noticing whether the words come with ease and conviction. If it’s easy to say and feels like a ‘yes,’ it’s likely aligned. Be mindful of social expectations and people‑pleasing tendencies — the Ego/Heart loses power when you sacrifice your own priorities. Protect honest expression and commit to what truly matters to you."
                    to "Твоят авторитет е Его/Сърце — решенията следват онова, което сърцето истински желае и което подкрепя волята и интересите ти. Тук практиката включва да произнесеш избора си на глас и да усетиш дали думите звучат уверено и естествено. Ако е лесно да го кажеш и се усеща „да“, вероятно е в синхрон с теб. Бъди внимателен към социални очаквания и склонността да угодиш — Его/Сърцето губи сила, когато жертваш собствените си приоритети."
        ),
        HdAuthority.SELF_PROJECTED to (
            "Your authority comes from the G/Self Center — your sense of identity, direction, and love. It guides you toward choices that resonate with who you are and your longer‑term trajectory. Talk through significant decisions with trusted people not to hand them the answer, but to hear how your words land externally. Notice which direction feels most ‘you’ and whether the choice contributes to a sense of wholeness and purpose. Speaking your intentions aloud often helps reveal and confirm the right path over time."
                    to "Твоят авторитет идва от G/Центъра на Аза — от усещането за идентичност, посока и любов. Той те води към избори, които резонират с това, което си и с дългосрочната ти посока. Обсъждай важните решения с доверени хора, не за да им дадеш власт над избора, а за да чуеш как твоите думи звучат отвън. Обърни внимание коя посока се чувства най‑„ти“ и дали изборът допринася за цялост и смисъл. Твоят говор често разкрива вътрешната ти истина и помага да потвърдиш посоката."
        ),
        HdAuthority.MENTAL to (
            "You don't have a single internal authority; your guidance is shaped by environment and mental reflection. Use trusted people as sounding boards to hear how you articulate your thoughts, rather than to take their advice as definitive. The right setting and supportive company often reveal what matters to you. Allow time to process impressions, seek calm, nonjudgmental spaces, and notice how different environments shift your sense of clarity before committing to important choices."
                    to "Нямаш вътрешен авторитет в класическия смисъл — твоят авторитет е разположен във външната среда и в менталния процес. Разговаряй с доверени хора и използвай събеседници като огледала, не за да получаваш готови решения, а за да чуеш как формулираш мислите си. Правилната обстановка и хората около теб често осветяват това, което ти е важно. Да реагираш след период на обмисляне и да създадеш спокойна, ненатоварваща среда може да ти помогне да намериш яснота и увереност."
        ),
        HdAuthority.LUNAR to (
            "As a Reflector, the lunar cycle functions as your authority — important decisions tend to benefit from the full moon cycle. Give yourself about 28 days to observe how your feelings and perspective shift as the Moon moves through your chart. Talk with a variety of people, gather different reactions, and keep notes so you can track emerging patterns. Resist pressure for immediate answers; letting the cycle unfold helps you arrive at choices that feel genuinely aligned."
                    to "Като Рефлектор решенията ви узряват по-бавно и е полезно да наблюдавате как се променя усещането ви в рамките на лунния цикъл. Преди важен избор дайте си около 28 дни, ако обстоятелствата го позволяват, и говорете с различни хора, за да видите какво остава важно след първоначалния импулс. Ще разпознаете подходящия момент, когато една и съща посока продължава да ви се струва правилна, вместо да разчитате на моментно настроение. Дневникът и достатъчно време без натиск могат да ви помогнат да вземете по-спокоен и последователен избор."
        )
    )

    // ── Profiles ──────────────────────────────────────────────────────────────
    val profileInfo: Map<String, Pair<String, String>> = mapOf(
        "1/3" to ("Investigator/Martyr: You need a solid foundation of knowledge before acting. You learn primarily through trial and error — your 'mistakes' are your greatest teacher and data source."
                to "Изследовател/Мъченик: Имаш нужда от солидна основа от знания преди да действаш. Учиш се главно чрез проба и грешка — твоите \"грешки\" са най-великият ти учител и източник на данни."),
        "1/4" to ("Investigator/Opportunist: You need deep personal foundations, and your opportunities come through your social network. Research thoroughly, then share what you've mastered with trusted connections."
                to "Изследовател/Опортюнист: Имаш нужда от дълбоки лични основи, а твоите възможности идват чрез социалната ти мрежа. Проучи задълбочено, след което сподели онова, което си овладял, с доверени връзки."),
        "2/4" to ("Hermit/Opportunist: You have natural talents you may not even be aware of. You need time alone to develop them, but your opportunities come through your network. The right call from the right person can change your life."
                to "Отшелник/Опортюнист: Имаш природни дарби, за които може дори да не знаеш. Имаш нужда от самота за да ги развиеш, но твоите възможности идват чрез мрежата ти. Правилното обаждане от правилния човек може да промени живота ти."),
        "2/5" to ("Hermit/Heretic: You are projected onto as a 'savior' or practical problem-solver, even if you don't see yourself that way. You need solitude to recharge, yet the world calls on your unconscious gifts to fix things."
                to "Отшелник/Еретик: Другите те проектират като 'спасител' или практически решавач на проблеми, дори ако ти не се виждаш така. Имаш нужда от самота за зареждане, но светът призовава несъзнателните ти дарби да поправят нещата."),
        "3/5" to ("Martyr/Heretic: You learn through life experience — bonds that work and don't work, jobs tried and rejected. This experiential wisdom makes you a practical, karmic teacher who others turn to for real-world solutions."
                to "Мъченик/Еретик: Учиш се чрез житейски опит — връзки, които работят и не работят, работи, опитани и отхвърлени. Тази придобита мъдрост те прави практически, кармичен учител, към когото другите се обръщат за решения в реалния живот."),
        "3/6" to ("Martyr/Role Model: Three life phases — first half spent in trial and error, then a period of stepping back and observing, then becoming a wise role model embodying the lessons of your experience."
                to "Мъченик/Ролеви модел: Три жизнени фази — първата половина в проба и грешка, след това период на отдръпване и наблюдение, после ставане на мъдър ролеви модел, въплъщаващ уроците от опита ти."),
        "4/6" to ("Opportunist/Role Model: Your opportunities come through your close personal network. In the first half of life you build those networks; in the second half you become a trusted role model who others look to for guidance."
                to "Опортюнист/Ролеви модел: Твоите възможности идват чрез близката ти лична мрежа. В първата половина на живота изграждаш тези мрежи; в втората ставаш доверен ролеви модел, към когото другите се обръщат за насоки."),
        "4/1" to ("Opportunist/Investigator: You need a stable personal foundation to feel secure, and opportunities come through your network. You must build solid knowledge before you can comfortably share with others."
                to "Опортюнист/Изследовател: Имаш нужда от стабилна лична основа за да се чувстваш сигурен, и възможностите идват чрез мрежата ти. Трябва да изградиш солидни знания преди удобно да споделяш с другите."),
        "5/1" to ("Heretic/Investigator: You are projected onto by others as someone who can 'save' or provide universal solutions. You need solid foundations to avoid the projection trap. Fame (and infamy) come easily to you."
                to "Еретик/Изследовател: Другите те проектират като някой, който може да 'спаси' или да предостави универсални решения. Имаш нужда от солидни основи за да избегнеш капана на проекцията. Слава (и лоша слава) ти идват лесно."),
        "5/2" to ("Heretic/Hermit: Your unconscious gifts are sought out by others who project great practicality onto you. You need significant alone time to recharge, yet you are constantly called upon by the world to step in and fix things."
                to "Еретик/Отшелник: Несъзнателните ти дарби са търсени от другите, които проектират голяма практичност върху теб. Имаш нужда от значително самотно време за зареждане, но светът постоянно те вика да се намесиш и поправиш нещата."),
        "6/2" to ("Role Model/Hermit: Three phases of life — a first phase of trial and error (Lines 3&2), a second phase of going 'on the roof' to observe and reflect, and a third phase after ~50 of living as a trusted, embodied role model."
                to "Ролеви модел/Отшелник: Три жизнени фази — първа фаза на проба и грешка (Линии 3&2), втора фаза на 'качване на покрива' за наблюдение и размисъл, и трета фаза след ~50 години на живеене като доверен, въплътен ролеви модел."),
        "6/3" to ("Role Model/Martyr: You embody wisdom through lived experience. The first half of life is rich with lessons through trial and error; the second half is about becoming the lived example others look to for authentic guidance."
                to "Ролеви модел/Мъченик: Въплъщаваш мъдрост чрез преживян опит. Първата половина на живота е богата с уроци чрез проба и грешка; втората половина е за ставане на живия пример, към когото другите се обръщат за автентично напътствие.")
    )

    // ── Definition ────────────────────────────────────────────────────────────
    val definitionInfo: Map<HdDefinition, Pair<String, String>> = mapOf(
        HdDefinition.SINGLE to (
            "Single Definition means your defined centers form one continuous circuit, giving you steady, self-contained energy. You often experience consistency and reliability in how you think, act, and make decisions, and you don't typically need others to 'complete' your energy. While independence is a strength, intentional relationships and collaborations can still enrich your life. Seek partnerships that respect your autonomy while offering practical support when you choose to connect."
                    to "Единична дефиниция означава, че всичките ти дефинирани центрове са свързани в един непрекъснат веригов модел. Това ти дава последователна, предвидима и самодостатъчна енергия — често усещаш поток и стабилност в решенията и работата си. Може да предпочиташ автономия и да не търсиш енергийно 'допълване' отвън. Въпреки това, ценните връзки и сътрудничествата могат да обогатят опита ти; работи със социални пространства, които уважават твоята независимост, но предлагат подкрепа, когато ти е нужна."
        ),
        HdDefinition.SPLIT to (
            "Split Definition means your defined centers form two distinct groupings, and you naturally seek people, contexts, or transits that bridge those groups. This tendency often makes you adaptable and receptive to multiple perspectives, but it can also create a sense of incompleteness when the bridge is missing. Allow relationships and circumstances to emerge that help connect your inner parts. Give yourself time to recognize which external connections truly harmonize your experience rather than forcing quick fixes."
                    to "Сплит дефиницията показва, че твоите дефинирани центрове се групират в две отделни вериги. Инстинктивно търсиш хора, ситуации или транзити, които да създадат мост между тези групи и да донесат усещане за цялост. Тази структура често води до гъвкавост — по-лесно възприемаш различни гледни точки и роли. Понякога можете да се чувствaш раздвоен или да имате нужда от външна подкрепа, за да съединяваш частите си; давай си време да усетиш кой „мост“ работи най-добре за теб."
        ),
        HdDefinition.TRIPLE_SPLIT to (
            "Triple Split Definition has three separate groupings of defined centers, giving you pronounced adaptability and a preference for varied interactions. Your impressions and responses often arrive in waves as different circuits activate at different times, so you may need extra time to process and integrate experiences. You benefit from a wide range of people and environments — diversity often clarifies what resonates. Intentionally schedule quieter time to assimilate new information and avoid overwhelm from too many simultaneous inputs."
                    to "Тройната сплит дефиниция означава три отделни групи дефинирани центрове, което ти дава голяма адаптивност и нужда от разнообразие. Информацията и чувствата ти често идват на вълни, различни вериги се активират в различни моменти, затова може да ти е нужно повече време за интеграция. Облагодетелстваш се от контакти с различни типове хора и среди — колкото по-разнообразни са взаимоотношенията ти, толкова по-ясна може да стане картината. Планирай периоди за обработка и усвояване на впечатленията, за да избегнеш претоварване."
        ),
        HdDefinition.QUADRUPLE_SPLIT to (
            "Quadruple Split Definition, a rare pattern of four separate groupings, brings exceptional openness and responsiveness to many different people and environments. You can gain a great deal from the right community, as social context tends to shape your experience strongly. However, the abundance of inputs can also feel fragmenting if you don't curate your circles. Consciously choose supportive groups that help you feel grounded and give you space to integrate the diverse influences you encounter."
                    to "Четворната сплит дефиниция е рядка и означава четири отделни групи дефинирани центрове. Такъв тип дава изключителна отвореност и склонност да се влияеш от много различни хора и среди. Може да си особено чувствителен към общността и социалната обстановка; с правилната среда получаваш значителна подкрепа и вдъхновение. Внимавай с разсейването — избирай съзнателно хора и групи, които те заземяват и ти позволяват да усетиш вътрешна цялост въпреки множеството входове."
        ),
        HdDefinition.NONE to (
            "No Definition (Reflector): With all centers open, you naturally mirror the people and environments around you. This openness allows you to sample many roles and perspectives, providing a broad and sensitive reflection of human experience. Because you're porous energetically, it's important to choose settings and companions deliberately, establish routines for recharging, and use cycles—like the lunar rhythm—to pace decisions. Cultivating clear boundaries and restorative practices helps you harness this reflective gift."
                    to "Без дефиниция (Рефлектор): Всички центрове са отворени и недефинирани, което те прави чувствително огледало на хората и средата около теб. Тази отвореност е дар — можете да пробваш различни роли и да отразяваш широк спектър от човешки преживявания. В същото време лесно поемаш енергии от околните, затова е важно да избираш внимателно средата и хората, да създаваш ритуали за презареждане и да използваш лунния ритъм или други цикли за по-обмислени решения."
        )
    )

    // ── Centers ───────────────────────────────────────────────────────────────
    data class CenterInfo(val defined: Pair<String, String>, val undefined: Pair<String, String>)

    val centerInfo: Map<HdCenter, CenterInfo> = mapOf(
        HdCenter.HEAD to CenterInfo(
            defined = ("Defined Head: You have a steady source of mental pressure and inspiration, frequently generating questions, doubts, and creative sparks on your own. Others may be drawn to your ideas and intellectual energy. To make this mental vitality constructive, capture insights in notes, create space for reflection, and practice discernment so thinking doesn't become rumination. Learning to tell apart useful inspiration from habitual mental noise will help you apply your ideas with clarity and purpose.")
                    to ("Дефинирана глава: Имаш постоянен и надежден източник на ментален натиск, идеи и вдъхновение. Често генерираш въпроси, съмнения и творчески импулси без външно подтикване; другите може да се обръщат към теб за мисли и перспективи. Постарай се да канализираш този умствен поток практично — води записки, давай си време за размисъл и разграничение, за да не изпаднеш в прекалено размишление. Разпознаването на кога мислите са полезни и кога просто шум може да ти даде повече яснота."),
            undefined = ("Undefined Head: You tend to amplify and sample other people’s mental pressure, taking on ideas and questions that aren’t originally yours. You may feel compelled to think about subjects that don’t truly concern you. Practical wisdom is learning to notice the origin of thoughts — whose questions they are and when you’re merely echoing. Allow pauses and inner checks so you can distinguish your own concerns from ambient mental noise. That discernment lets you keep useful impressions as inspiration without adopting them as fixed beliefs.")
                    to ("Недефинирана Глава: Усилваш и пробваш менталния натиск на другите, приемащ идеи, емоционални теми и въпроси, които не са твои. Може да се почувствате задължен да размишляваш върху чужди дилеми или да решаваш проблеми, които не ти принадлежат. Практиката тук е да отбелязваш откъде идват мислите — чии са въпросите, кои очакват отговор — и да си даваш паузи за разпознаване. Когато разграничиш собствените си въпроси, можете да използваш получените впечатления като вдъхновение, без да ги превръщаш автоматично в свои убеждения.")
        ),
        HdCenter.AJNA to CenterInfo(
            defined = ("Defined Ajna: You have a steady, repeatable way of processing information and forming opinions. Your thinking tends to be structured and reliable, which supports clear decisions and consistent expression. This can be an asset in roles where intellectual steadiness matters, though it may sometimes make you resistant to novel perspectives. It helps to test your assumptions, seek feedback, and intentionally expose yourself to differing viewpoints so your certainty remains useful rather than limiting.")
                    to ("Дефинирана Аджна: Имаш стабилен и повтарящ се начин за обработка на информация и оформяне на мнения. Мисленето ти обикновено е структурирано и последователно, което ти дава надеждност при вземане на решения и изразяване на възгледи. Това може да бъде силно в роли, които изискват яснота и последователност, но носи и риск от закостенялост или съпротива към нови идеи. Полезно е да практикуваш проверка на предположенията си и да търсиш обратна връзка, за да останеш открит към допълващи гледни точки."),
            undefined = ("Undefined Ajna: You have a flexible, adaptable mind that can consider ideas from many angles. You often shift perspective with ease and can synthesize diverse viewpoints. That versatility is valuable, but it also carries the tendency to borrow others’ beliefs or to appear certain when you’re not. A constructive approach is to acknowledge uncertainty openly, ask clarifying questions, and treat incoming opinions as resources to explore rather than fixed answers. This preserves your mental freedom and integrity.")
                    to ("Недефинирана Аджна: Имаш гъвкав и адаптивен ум, способен да разглежда идеи от множество ъгли. Често можете да променяш перспективата си според контекста и да намериш нестандартни решения. В същото време има риск да поемеш мнения наоколо или да се преструваш на сигурен, когато всъщност си несигурен. Практиката тук е честно да признаваш несигурността, да задаваш въпроси и да използваш разнообразието от виждания като ресурс, без да се задържаш дълго върху чужди убеждения.")
        ),
        HdCenter.THROAT to CenterInfo(
            defined = ("Defined Throat: You have a consistent voice and presence that can reliably initiate communication and attract attention. Your words often shape situations — in conversation, performance, or the practical manifestation of ideas. This gives you a natural edge for leadership in expression, but it can also incline you to dominate or speak before reflecting. Balancing initiative with active listening and choosing intentional moments to use your voice will make your expression both influential and responsible.")
                    to ("Дефинирано Гърло: Имаш последователен глас и присъствие, което може да иницира комуникация и да привлича внимание. Думите ти често имат сила да оформят ситуации — в лични разговори, изяви или практическа проява на идеи. Това ти дава възможност за лидерство в изразяването, но може и да предизвика склонност да доминираш или да говориш преждевременно. Полезно е да балансираш инициативността с слушане и да избираш моментите, в които да канализираш гласа си целенасочено."),
            undefined = ("Undefined Throat: You’re naturally a good listener who absorbs others’ communication styles and can mirror different tones of expression. You may feel pressure to speak to gain attention, yet the wiser path is often to wait for an invitation or the right moment. When you do speak after being invited, your words can feel uniquely authentic and striking. Simple practices like pausing before replying and checking your motives help protect your own voice while using your capacity to reflect and connect.")
                    to ("Недефинирано Гърло: По природа си добър слушател и приемаш стиловете на общуване на другите — можете да отразяваш различни тонове и начин на изразяване. Понякога може да почувствате натиск да говориш, за да привлечеш внимание, но мъдростта е да изчакваш покана или подходящия момент. Когато решиш да говориш след покана, думите ти често звучат открояващо и автентично. Практики като пауза преди отговор и проверка на мотивите ти помагат да запазиш собствения си глас.")
        ),
        HdCenter.G to CenterInfo(
            defined = ("Defined G Center: You tend to have a steady sense of self, identity, and direction in life. You often know who you are and where you want to go, even if the exact route isn’t clear. That constancy provides an inner compass that shapes relationships and the environments you gravitate toward. It can sometimes lead to resistance to change; periodically checking whether your stability still serves your growth and allowing space to revise goals will keep your identity both grounded and responsive.")
                    to ("Дефинирано G Център: Имаш сравнително стабилно усещане за себе си, идентичност и посока в живота. Често знаеш кой си и къде би искал да отидеш, дори когато пътят не е напълно ясен. Тази постоянност ти дава вътрешен компас, който влияе на връзките и избора ти на среди. Възможно е да проявяваш малко устойчивост към промяна; полезно е да проверяваш дали устойчивостта подкрепя растежа ти и да си оставяш пространство за преразглеждане на целите, когато е необходимо."),
            undefined = ("Undefined G Center: Your sense of identity and direction tends to shift depending on the people and places you’re with. This is a gift of adaptability rather than a flaw — you can try on different selves and respond fluidly to context. The downside can be occasional disorientation about who you are or where you’re heading. It helps to notice which environments and relationships make you feel most authentic and to seek those contexts when you need an anchor, while honoring the creativity in your changing self-expression.")
                    to ("Недефиниран G Център: Твоето усещане за идентичност и посока е по-сложно и се променя според хората и местата около теб. Това не е недостатък, а дар — ти имате способността да се адаптираш и да се оглеждаш в средата си. Предизвикателството е временната загуба на център или объркване относно коя версия на себе си да следваш. Полезно е да отбелязваш кои обстановки и взаимоотношения те правят да се чувствате най-истински и да търсиш такива пространства, когато имате нужда от опора.")
        ),
        HdCenter.HEART to CenterInfo(
            defined = ("Defined Heart/Ego: You have consistent access to willpower, a sense of self-worth, and the drive to engage with the material world. That enables you to make commitments and follow through, to claim and protect what you value. It’s important to commit only to what genuinely reflects your priorities and to honor your need for rest after exertion. Watch for tendencies to prove worth through overwork or competitiveness; set boundaries and manage your energy and resources consciously so your will serves you sustainably.")
                    to ("Дефинирано Сърце/Его: Имаш стабилен достъп до воля, чувство за собствена стойност и енергията на материалния свят. Това ти позволява да поемаш ангажименти и да ги изпълняваш, да искате и да защитаваш това, което цениш. Важно е да се ангажираш само с проекти и взаимоотношения, които наистина отразяват твоите приоритети, и да почиташ нуждата си от почивка след усилие. Внимавай със склонността да доказваш стойността си чрез прекомерна работа или съревнование — поставяй граници и управлявай ресурсите си съзнателно."),
            undefined = ("Undefined Heart/Ego: Your willpower often fluctuates — sometimes it's present, sometimes it isn't. This variability is natural and not a flaw; you are not designed for steady, ongoing ego-driven will. Practically, it helps to be transparent about your changing capacity so you avoid overcommitting or proving your worth in bursts of high energy. Use short-term commitments, clear boundaries, and honest communication about what you can deliver; rest and recalibration are legitimate and necessary strategies.")
                    to ("Недефинирано Сърце/Его: Твоята воля често варира — понякога имате решимостта, друг път не. Това е естествено и не означава слабост; не си проектиран да поддържаш постоянна волева енергия. Практика на честност към себе си и другите за твоята непостоянност може да предотврати изтощение и разочарования. Полезно е да избягваш да доказваш своята стойност чрез обещания, които правите в моменти на висок заряд; вместо това използвай краткосрочни ангажименти, ясни граници и комуникация за настоящите си ресурси.")
        ),
        HdCenter.SACRAL to CenterInfo(
            defined = ("Defined Sacral: You carry a strong motor for life, work, and sexuality — your energy typically renews overnight and is available again each morning. You are designed to respond from the gut; simple yes/no impulses guide you toward satisfying activity. Aim to shape routines and commitments that respect your energy cycles, allow for bursts of focused work, and protect against chronic depletion. Listening to what genuinely energizes you helps you apply this power sustainably and avoid doing energy-draining tasks out of obligation.")
                    to ("Дефиниран Сакрален: Имаш мощен двигател за живот, работа и сексуалност — енергията ти се възстановява през нощта и често е налична за нов ден. Проектиран си да откликваш „с червата“; интуитивните отговори (да/не) те насочват към удовлетворяваща дейност. Полезно е да търсиш работа и връзки, които приемат твоите енергийни цикли, да планираш интензивни периоди на продуктивност и да се пазиш от хронично пренатоварване, като даваш приоритет на това, което наистина те зарежда."),
            undefined = ("Undefined Sacral: You don’t have a steady generative source and often absorb or amplify the sacral energy of those around you. That tendency can lead to taking on more than you can sustain. It’s important to honor your need for rest, set boundaries, and resist working as if you had a defined sacral rhythm. Practical measures — scheduling breaks, saying no to persistent requests, and choosing projects that truly feel right — protect your health and keep your energy balanced.")
                    to ("Недефиниран Сакрален: Нямаш постоянен генеративен източник и често усилваш сакралната енергия на хора около себе си. Това може да доведе до приемане на повече задачи или ангажименти, отколкото можете да поддържаш. За благосъстоянието ти е важно да зачитащ нуждата от почивка, да поставяш граници и да избираш кога да откликваш. Практики като ясни работни периоди, междинни почивки и честни разговори за възможностите ти помагат да работите устойчиво без изгаряне.")
        ),
        HdCenter.SPLEEN to CenterInfo(
            defined = ("Defined Spleen: You have steady access to intuition, immune awareness, and primal sensing — your body often knows instantly what is healthy or harmful. This immediate guidance can be reliable for quick practical choices about food, environment, or timing. It’s useful to honor these quiet impulses rather than over-rationalize them, and to build practices that tune you in (grounding, brief checks-in, simple self-care rituals). At the same time, allow space to differentiate instinctual signals from fear-driven reactions.")
                    to ("Дефинирана Слезка: Имаш постоянен достъп до интуиция, имунна чувствителност и първични усещания — тялото ти често знае мигновено кое е полезно или вредно. Това интуитивно осъзнаване може да те води в малки, бързи решения за здраве и среда. Важно е да цениш тези тихи импулси и да им създаваш пространство, вместо да ги рационализираш или пренебрегваш. Упражнения в присъствие, слушане на телесни сигнали и леки ритуали за самообгрижване могат да засилят това природно знание."),
            undefined = ("Undefined Spleen: You tend to amplify others’ fears and well-being signals and may stay attached to people, jobs, or habits that feel comfortable in the moment but aren’t healthy long-term. The skill is learning to distinguish your own somatic cues from amplified input and to create boundaries that support clearer choices. Practical approaches — pausing before big health decisions, testing small changes, and building routines that honor rest — help you let go of what no longer serves your vitality.")
                    to ("Недефинирана Слезка: Усилваш страховете и здравните осъзнавания на хората около теб и можете да задържиш връзки, места или навици, които не са дългосрочно полезни — защото в момента изглеждат „добри“. Мъдростта е да развиваш способността да разграничиш какво е твое усещане и какво прилича на чуждо усилване, и да създадеш ритми и граници, които подпомагат спокоен избор. Малки, постепенни стъпки да пускаш това, което вреди на здравето ти, могат да се окажат най-устойчивата промяна.")
        ),
        HdCenter.SOLAR_PLEXUS to CenterInfo(
            defined = ("Defined Solar Plexus: You move along an emotional wave of highs and lows — that variability is part of your nature and not something to be fixed. For you, clarity often unfolds over time; the present moment may not reveal the whole truth. Practically, waiting through emotional cycles before making major choices, communicating your tempo to others, and using processing tools (journaling, talking it through) reduce impulsive moves and lead to decisions that feel more aligned once the wave settles.")
                    to ("Дефиниран Слънчев Сплит: Твоят емоционален ритъм често се движи между върхове и долини — това е естествената ти динамика и не е нещо, което трябва да „поправяш“. За теб яснотата обикновено идва с времето; моментните емоции могат да бъдат заблуждаващи. Практически, изчакването преди важни решения, откровена комуникация с близки за твоите емоционални цикли и изграждането на ритуали за обработване на чувства ти помагат да взимате решения с по-малко съжаление и по-голямо вътрешно равновесие."),
            undefined = ("Undefined Solar Plexus: You often absorb and amplify the emotions of those around you, feeling others’ feelings as if they were your own. This sensitivity can be a gift when you learn to manage it. Useful strategies include grounding techniques, naming which emotions belong to you, and allowing time to process before responding or deciding. Practicing compassionate boundaries and not rushing to fix others’ emotional states preserves your energy and helps you respond from a clearer space.")
                    to ("Недефиниран Слънчев Сплит: Често поглъщаш и усилваш емоциите на хората около себе си — може да усещаш чуждите чувства като свои. Тази чувствителност е дар, когато е разпозната и управлявана. Полезно е да развиваш практики за заземяване, да именуваш какво е твое и какво не, и да отделяш време за емоционално пречистване преди да вземаш решения. Научаването да не „поправяш“ автоматично емоционалните състояния на другите ще съхрани енергията и яснота ти.")
        ),
        HdCenter.ROOT to CenterInfo(
            defined = ("Defined Root: You carry a fairly steady adrenal pressure that propels you to finish tasks and move through life at your own pace. That pressure is your engine, but discernment matters — notice when you’re rushing merely to relieve tension versus responding to a genuine drive. Channel this force with focused sprints, scheduled breaks, realistic prioritization, and relaxation practices so it serves productivity without tipping into chronic stress or impatience with slower rhythms.")
                    to ("Дефиниран Корен: Имаш относително постоянен адреналинов импулс, който те тласка да довършваш задачи и да се движиш с определено темпо. Това налягане е твоят двигател, но е важно да различаваш кога ускоряваш за да облекчиш напрежение и кога действително откликваш на вътрешен импулс. Канализирай го чрез структурирани периоди на интензивна работа, редовни паузи и практики за отпускане, за да избегнеш хроничен стрес и да запазиш устойчиво темпо."),
            undefined = ("Undefined Root: You often absorb and amplify the adrenal stress of people around you, which can make you rush to relieve the pressure. That urgency may lead to hasty choices or fatigue. A constructive approach is to learn to tell external pressure apart from your own impulses: pause, breathe, and allow time before deciding. You can set gentle boundaries, create small rituals to regulate your energy, and use your sensitivity as information rather than obligation. Slowing down can reduce reactive behaviour and help you respond from clarity rather than anxiety.")
                    to ("Недефиниран Корен: Често поглъщаш и усилваш адреналиновия стрес на хората около теб — усещаш натиска като собствен и може да бързаш, за да го облекчиш. Това води до импулсивни решения и умора. Практически подход е да се научиш да разпознаваш кога е външен натиск и кога е твой собствен импулс: поемай дълбоко дъх, забавяй темпото и давай си време преди да действаш. Може да поставяш граници, да използваш паузи или ритуали за регулиране и да превърнеш своята чувствителност в информация, а не в задължение.")
        )
    )

    // ── Channels ──────────────────────────────────────────────────────────────
    val channelInfo: Map<String, Pair<String, String>> by lazy {
        val map = mutableMapOf<String, Pair<String, String>>()
        // Key is "min-max" gate numbers
        fun key(a: Int, b: Int) = "${minOf(a,b)}-${maxOf(a,b)}"

        map[key(1,8)]   = "Inspiration (1-8): The channel of creative individual expression. You often feel a steady drive to be seen and heard through your unique ideas and style. Your creative output can naturally inspire others, though it may also bring a desire for recognition. Practical guidance is to cultivate regular creative habits, share work in manageable steps, and focus on authenticity rather than one-off validation. Over time, consistent expression tends to build influence and deeper resonance more reliably than chasing immediate applause." to "Вдъхновение (1-8): Каналът на творческото индивидуално изразяване. Често имате постоянна нужда да бъдеш видян и чут чрез своите оригинални идеи и стил. Творческата ти енергия може лесно да вдъхнови другите, но също така да създава очаквания за признание. Практически съвет е да работите последователно, да създаваш навици за продукция и да споделяш творбите си на стъпки, вместо да търсиш еднократен успех. Автентичността и постоянството често говорят по-силно от кратката видимост."
        map[key(2,14)]  = "The Beat (2-14): The channel of the keeper of the keys. You have a natural, magnetic quality that can direct life-force energy and often draws others toward your direction, even without effort. That attraction may bring responsibilities or expectations to lead. Balance comes from being intentional about your influence: lead by example, set clear boundaries, and choose when to step forward. When managed with care, your magnetism can be a powerful resource for guiding, organizing, and supporting those around you." to "Ритъмът (2-14): Каналът на пазителя на ключовете — имате магнитично качество, което насочва жизнената енергия и често привлича хора към твоята посока, дори когато не се стараеш. Това може да носи отговорности или очаквания да водиш. Балансът идва от да бъдеш съзнателен в начина, по който оказваш влияние: показвай пример чрез действия, установявай ясни граници и избирай кога да поемеш водеща роля. Твоята притегателност е ресурс, който може да се използва за подкрепа и организиране, ако го управляваш с внимание."
        map[key(3,60)]  = "Mutation (3-60): The channel of energy mutation. You may feel pressure to break through limitations and introduce something new; change tends to come in bursts rather than on a schedule. That pattern can feel disruptive and unpredictable, yet creative and generative. It helps to experiment, allow recovery and integration between surges, and avoid forcing progress. By giving transformation space to unfold, you often allow more sustainable, genuinely novel outcomes to emerge instead of rushed or temporary fixes." to "Мутация (3-60): Каналът на енергийна мутация. Често усещаш натиск да преодолееш ограничения и да внесеш нещо ново — промяната идва на вълни и не може да бъде форсирана. Това може да бъде бурно и непредвидимо, но и плодотворно. Полезно е да се подготвяш чрез експерименти, да оставяш пространство за интеграция между тласъците и да приемаш цикличността на процеса. Когато позволяваш на промяната да се оформя постепенно, тя често носи по-устойчив и иновативен резултат."
        map[key(4,63)]  = "Logic (4-63): The channel of mental logic and doubt. You often feel compelled to question patterns and seek evidence, which equips you to bring rigor to collective understanding. That critical edge can be invaluable, but it may also lead to over-analysis or alienation if unchecked. Practical guidance is to pair rigorous inquiry with patience and empathy: frame insights as hypotheses, invite feedback, and apply your analytical gifts to clarify rather than only to dismiss. This makes your contributions both sharp and constructive." to "Логика (4-63): Каналът на ментална логика и съмнение. Често усещаш вътрешен натиск да поставяш под въпрос модели и да търсиш доказателства, което ти дава способността да внасяш логическа строгост в общото разбиране. Внимание: склонността към скептицизъм може да води до анализаторски блокажи или отчуждение. Практическо насочване е да комбинираш критичното мислене с търпение и емпатия — представяй своите аргументи като работни хипотези и даваш пространство за обратна връзка."
        map[key(5,15)]  = "Rhythm (5-15): The channel of natural rhythms and timing. You have a distinct relationship with time and flow; your life often moves in cycles, and honoring your own rhythm can make things run more smoothly. When you ignore it, external schedules or pressures can create tension and friction. Helpful practices include establishing rituals, noticing when you’re in a creative peak or need rest, and communicating your timing to others so you can better align personal tempo with shared commitments." to "Ритъм (5-15): Каналът на естествените ритми и времето. Имаш уникална връзка с времето и потока — животът ти се движи в цикли и когато уважаваш собствения си ритъм, много неща текат по-лесно. В противен случай външните графици и очаквания могат да създадат напрежение и чувство на дисхармония. Полезно е да изработите ритуали, да разпознаваш периодите на продуктивност и почивка и да комуникираш нуждите си, така че да синхронизираш личния си темп с изискванията на средата."
        map[key(6,59)]  = "Mating (6-59): The tribal channel of sexuality and intimacy. You often feel a powerful urge for deep bonding and mutual sharing; your energy can dissolve barriers and foster genuine trust. That intensity can also create vulnerability, possessiveness, or pressure if boundaries are unclear. Practical guidance is to cultivate honest communication, explicit expectations, and consent. Channel your drive toward mutual support and reciprocity, using openness to deepen connection rather than to compensate for unmet needs." to "Чифтосване (6-59): Племенният канал на сексуалността и интимността. Често изпитваш силно желание за дълбока връзка и споделяне; твоята енергия може да събаря бариери и да създава доверие. Това интензивно поле може да породи уязвимост, притежание или пресилване на близостта, ако не са ясни границите. Практическо насочване: култивирай искрен диалог, ясни очаквания и съгласие; използвай своята сила, за да изграждаш взаимна подкрепа, а не да запълваш лични липси."
        map[key(7,31)]  = "The Alpha (7-31): The channel of influence and leadership. You often possess a natural ability to guide others toward the future; your voice can attract attention and direction. That capacity offers opportunities to inspire, yet it can also bring pressure to take on too much or to dominate. Aim to lead by invitation and example, stay accountable, welcome feedback, and delegate where appropriate. Leading with empathy and transparency helps your influence feel trustworthy and sustainable to those who follow." to "Алфата (7-31): Каналът на влиянието и лидерството. Често имате естествена способност да насочваш другите към бъдещето и твоят глас може да привлича внимание и посока. Това носи възможност за вдъхновение, но също и риск от поемане на прекалена отговорност или доминиране. Съветът е да водиш чрез покана и пример, да останеш отговорен и отворен към обратна връзка, да делегираш и да развиваш съпричастност — така влиянието ти става устойчива и приемана от останалите."
        map[key(9,52)]  = "Concentration (9-52): The channel of focus and detail. You often have the capacity to concentrate deeply and notice what others miss. This channel encourages sustained attention and persistence on a specific subject, which can be valuable for research, craft, troubleshooting, or any work that requires fine discrimination. Tensions may include tunnel vision or overworking; practical expression involves structuring deep-work periods, taking regular breaks, and deliberately shifting perspective to balance precision with the larger picture." to "Концентрация (9-52): Каналът на фокуса и детайла. Често притежаваш възможността да се съсредоточиш дълбоко и да забелязваш онова, което другите пропускат. Този канал насочва към устойчиво внимание и усърдна работа по един конкретен обект или задача. В практиката това може да се прояви в научни изследвания, занаятчийство или аналитична работа. В същото време е полезно да наблюдаваш склонността към обсесивност и да отмерваш времето за почивка, за да запазиш перспектива и креативност."
        map[key(10,20)] = "Awakening (10-20): An integration channel where the behavior of the Self is expressed in the now. This energy often aligns self-regard with present-moment awareness so that authentic action becomes a clear communication of where you’re headed. It can show up as quiet leadership, making choices that model integrity, or sudden clarity about how to live your values. Tensions may include feeling exposed or second-guessing. Practical suggestions: start with small acts of authenticity, notice how others respond, and use moment-to-moment awareness to refine your conduct." to "Пробуждане (10-20): Интеграционен канал. Тук поведението на Аза се проявява в настоящия момент — твоето автентично действие може да говори по-силно от думите. Каналът насочва към интегрирането на себелюбието и осъзнатия избор: когато действаш в синхрон с вътрешната си истина, поведението ти естествено показва посоката. Това може да бъде начин на ежедневно лидерство или тихо водене чрез пример. Възможни са усещания за уязвимост и съмнение; полезно е да практикуваш малки, честни стъпки и да оценяваш реакциите, без да губиш вътрешната си ориентация."
        map[key(10,34)] = "Exploration (10-34): An integration channel emphasizing the power of following one’s convictions. You may feel a strong drive to live by your own rules and to investigate what authenticity means in practice, regardless of others’ opinions. This energy supports bold experiments, personal responsibility, and the refinement of a unique life approach. Potential tensions include social friction or stubbornness. Constructive expression involves testing beliefs in real situations, learning from feedback selectively, and remaining open to adapting your approach as you gain experience." to "Изследване (10-34): Интеграционен канал. Силата на следване на собствените убеждения често те подтиква да живееш по свои правила и да изследваш какво означава да бъдеш истински себе си. Този канал подкрепя експериментите, смелите избори и индивидуалната отговорност за последствията. В позитивна изява можете да бъдеш пионер в морални или житейски въпроси; в напрежение — да срещаш съпротива или да отхвърляш полезна обратна връзка. Практиката включва внимателно изпробване на убежденията, събиране на данни от опита и гъвкавост при необходимост."
        map[key(10,57)] = "Perfected Form (10-57): An integration channel linking intuitive survival cues to authentic behavior. You may receive strong somatic or instinctive signals that steer you toward what feels healthy and safe in a given moment. This can support rapid adaptation, wise self-care, and choices that preserve well-being. Tensions can arise when fear is mistaken for intuition or when impulses are acted on without testing. Practical guidance: cultivate body awareness, pause to sense whether a response is habitual or genuinely informative, and apply instincts incrementally to build trust." to "Перфектна Форма (10-57): Интеграционен канал. Интуитивното оцеляване се проявява чрез автентично поведение — имате усещането за телесни и интуитивни сигнали, които те насочват към това, което е здравословно и безопасно в момента. Този канал може да даде бърза адаптивност и усет за подходящи избори в лично и професионално поле. Възможни предизвикателства са объркване между страх и интуиция или импулсивни реакции; полезно е да развиваш смирено доверие към телесните усещания и да проверяваш импулсите в действие постепенно."
        map[key(11,56)] = "Curiosity (11-56): The channel of the storyteller. You are often driven to seek new ideas and experiences and to shape them into stories that inspire and connect. Your gift can appear in writing, speaking, teaching, or any medium that translates novelty into meaning for others. Challenges include a tendency toward sensationalism or pursuing novelty for its own sake. Useful practices: pair curiosity with careful observation, honor factual nuance, and use storytelling to illuminate others’ perspectives as well as your own." to "Любопитство (11-56): Каналът на разказвача. Често те движи търсенето на нови идеи и преживявания и желанието да ги превърнеш в истории, които вдъхновяват и свързват. Твоят дар може да бъде в споделянето на въздействащи разкази — чрез писане, говорене или артистични форми. Предизвикателства включват склонност към преувеличение или да търсиш вълнение заради самото вълнение. Практически подход: развивай чувството за отговорност към истината, редувай новаторство с дълбочина и давай глас и на чуждите истории, не само на собствените."
        map[key(12,22)] = "Openness (12-22): The channel of grace and emotional expression. Your emotions often speak through sound, tone, and creative presentation — when you’re in the right emotional space, your voice can move others deeply. This energy lends itself to singing, spoken word, performance, or any vulnerable form of communication. Tensions include moodiness or mistiming emotionally charged messages. Helpful strategies: cultivate emotional regulation, choose contexts that support vulnerability, and learn how silence or restraint can amplify the effect of your expression." to "Откритост (12-22): Каналът на грацията и емоционалното изразяване. Твоите чувства често се проявяват през звук, тон и творческа форма — гласът и начинът на изразяване могат дълбоко да трогнат слушателите, когато си в подходящото емоционално пространство. Този канал насочва към артистична изява, публична комуникация и уязвимо споделяне. Възможни трудности са емоционалната нестабилност или изборът на неподходящ момент за изява; работи за регулиране на настроенията, подбор на ситуации и използване на паузи като инструмент за въздействие."
        map[key(13,33)] = "The Prodigal (13-33): The channel of the witness. You often act as a keeper of stories and confidences, gifted at listening deeply and later sharing the insight you’ve gathered at the right moment. This energy supports reflection, narrative wisdom, and the ability to transform experience into meaningful teaching. Potential tensions include the burden of secrecy or hesitation about when to speak. Practice discernment about timing and audience, honor confidentiality, and use your witnessing to foster healing and clear perspective rather than sensational disclosure." to "Блудният Син (13-33): Каналът на свидетеля. Често си пазител на истории и тайни — имате умението да слушаш внимателно и да наблюдаваш човешките процеси, за да споделиш мъдростта си в подходящия момент. Този канал насочва към ретроспекция, разказ и трансформация на преживяното в полезни уроци. Може да изпитваш тежестта на отговорността да пазиш довереността или да се колебаеш кога да говориш; полезно е да упражняваш дискриминация, да уважаваш времето за споделяне и да превръщаш личните свидетелства в емпатична подкрепа за другите."
        map[key(16,48)] = "The Wavelength (16-48): The channel of talent and mastery. You often have access to deep wells of skill and potential, with a predisposition to develop mastery in a chosen area through repetition, refinement, and joyful practice. This energy favors craft, technique, and gradual improvement that accrues into expertise. Tensions can include perfectionism or getting stuck chasing an ideal. Constructive approaches involve deliberate practice, feedback from mentors, balancing discipline with play, and setting milestones to celebrate incremental progress." to "Дължината на Вълната (16-48): Каналът на таланта и майсторството. Имате достъп до дълбоки извори на умения и потенциал — често се проявяват като устременост да усъвършенствате една област чрез повторение и фино настройване. Този канал насочва към радостта от практиката и към развиване на експертиза, която може да бъде както практическа, така и художествена. Предизвикателствата включват перфекционизъм или застой в търсенето на „съвършенството“; полезно е да прилагате целенасочена практика, да търсите менторство и да запазвате играта и любопитството в процеса."
        map[key(17,62)] = "Acceptance (17-62): The channel of logical organisation and opinion. You naturally organise information into coherent patterns and articulate structured viewpoints, which helps clarify systems and reduce confusion. This talent can streamline group decision-making and highlight practical improvements. Be mindful that clearly expressed opinions can be received as fixed or prescriptive; offering your insights as open suggestions, checking assumptions, and inviting dialogue often makes them more useful and less confrontational." to "Приемане (17-62): Каналът на логическата организация и мнението. Имаш склонност да подреждаш информацията в ясни, логически модели и да формулираш структурирани становища. Това често ти дава възможност да виждаш недоразумения и да предлагаш системни решения, които улесняват общото функциониране. Внимавай мненията ти да не звучат догматично — полезно е да оставяш място за обратна връзка, да проверяваш фактите и да представяш вижданията си като предложения, които могат да се дискутират и адаптират."
        map[key(18,58)] = "Judgment (18-58): The channel of incisive correction. You tend to spot what’s inefficient or flawed and can offer corrective measures that enhance communal vitality. This perceptive gift supports collective health when applied constructively and with good timing. Because corrective feedback can feel sharp, it helps to pair keen observation with empathy, frame suggestions as improvements rather than verdicts, and engage others in the process so change becomes collaborative rather than isolating." to "Съждение (18-58): Каналът на проницателната корекция. Имаш остро око за това, което е неизправно или подлежи на подобрение, и можете да предложиш практически корекции, които повишават жизнеспособността на групата. Този дар е ценен, когато е използван с чувствителност — критиката може да бъде полезна, ако е конструктивна и навременна. Работи върху начина на подаване: даваш повече полза, когато комбинираш точността с емпатия и насърчаваш участие в решаването на проблемите."
        map[key(19,49)] = "Synthesis (19-49): The tribal channel of sensitivity to needs. You are often deeply attuned to basic communal needs—food, shelter, belonging—and skilled at recognising gaps and mobilising resources to address them. This ability supports group resilience and practical survival. Pay attention to balance: the impulse to provide can lead to taking on too much alone, so inviting shared responsibility and creating systems for sustainable care tends to be more empowering for everyone involved." to "Синтез (19-49): Племенният канал на чувствителността към нуждите. Често си дълбоко усетлив към основните нужди — храна, подслон, подкрепа и принадлежност — на твоята общност. Твоят талант е да разпознаваш какво липсва и да организираш ресурси или решения, които да подпомогнат оцеляването и просперитета на „племето“. Внимавай да не поемаш твърде голяма отговорност самостоятелно; ефективно е да включваш и овластяваш други членове в грижата и разпределението на ресурсите."
        map[key(20,57)] = "The Brainwave (20-57): An integration channel for present-moment knowing. You often experience immediate intuitive clarity about what’s appropriate and safe now, and your presence can communicate that assurance to others. This makes you a natural example of embodied awareness. Because this expression can come through as sudden or direct, it helps to notice timing and context—speaking from presence is powerful, but pausing when necessary ensures your insight lands constructively." to "Мозъчната вълна (20-57): Интеграционен канал. Този канал насочва интуитивното осъзнаване, изразено в момента — бързо знание за това кое е правилно и безопасно тук и сега. Можеш да служиш като жив пример, чието присъствие успокоява и насочва останалите. В същото време директността може да изглежда импулсивна; полезно е да развиваш умението да разпознаваш кога да говориш веднага и кога да изчакаш, за да се случи по-благоразумна интеграция."
        map[key(21,45)] = "Money (21-45): The tribal channel of material mastery. You often have the will and practical skill to manage resources—budgets, logistics, stewardship—and may naturally take responsibility for your group's material wellbeing. This aptitude can stabilise and support others, but can also create friction if it becomes overly controlling. Cultivating transparency, fair delegation, and clear agreements about responsibilities and distribution helps sustain both effectiveness and trust." to "Пари (21-45): Племенният канал на материалното майсторство. Имаш волята и уменията да управляваш материални ресурси — планиране, контрол и грижа за финансите — и често поемаш ръководна роля в осигуряването на материално благополучие за общността. Това може да те направи ценен стопанин, но и да създаде напрежение, ако контролът стане прекомерен. Полезно е да развиваш прозрачност, делегиране и ясни правила за отговорност и споделяне."
        map[key(23,43)] = "Structuring (23-43): The channel of distinctive individual insights. You frequently receive sudden, restructuring insights that can shift how things are understood. The real work is translating those flashes into language and examples others can grasp. Try testing ideas in small, clear steps, refining explanations, and allowing time for others to assimilate new frames. Grounding visionary thoughts in simple practices or demonstrations makes them easier to share and sustain." to "Структуриране (23-43): Каналът на уникалните индивидуални прозрения. Получаваш внезапни, понякога неочаквани прозрения, които променят рамките, в които се разбират нещата. Предизвикателството е да преведеш тези интуитивни проблясъци в достъпни думи и примери, така че други да могат да ги схванат и приложат. Практикувай изпробване на идеите в малки стъпки, търпение и опростяване — това увеличава шанса прозренията ти да намерят разбиране и използване."
        map[key(24,61)] = "Awareness (24-61): The channel of mental mysticism. You often feel an inner pressure to explore the unknowable—to seek truths beneath surface appearances and probe existential questions. This creates a restless, searching mind drawn to paradox and depth. Balancing inquiry with practices that translate insights into creative expression or shared teaching helps prevent rumination; also, learning to tolerate unresolved mysteries can be as freeing as finding answers." to "Осъзнаване (24-61): Каналът на менталния мистицизъм. Често усещаш вътрешно натискане да проникнеш в непознатото — да търсиш „защо“-то зад явленията и смисъла на съществуването. Този ум е любопитен и неуморим, привлечен от дълбоки тайни и символи. Важно е да балансираш интелектуалното търсене с практика, която да превърне прозренията в творчество или споделено познание, и да допускаш, че някои мистерии остават отворени."
        map[key(25,51)] = "Initiation (25-51): The channel of cosmic shock. You may access a sense of universal love and be opened to higher consciousness through unexpected, sometimes intense experiences that function as initiations. These events can be both catalytic and exhausting, so integration—rest, reflection, and support—is important. Approached with care and humility, such transformations can deepen compassion, model resilience for others, and become a source of service rather than merely personal upheaval." to "Посвещение (25-51): Каналът на космическия шок. Имаш достъп до усещане за универсална обич и способност да бъдеш трансформиран чрез неочаквани, понякога силни преживявания, които отварят към по-широко съзнание. Тези „шокове“ могат да бъдат както пробуждащи, така и изтощителни; важно е да имате ресурси за интеграция и да подходиш с уважение към собственото темпо. Когато се работи осъзнато, преживяванията ти могат да вдъхновят другите и да служат на общото пробуждане."
        map[key(26,44)] = "Surrender (26–44): The tribal transmitter channel. You often have a natural gift for offering, persuading, and communicating what your community values. Your instinct about what the tribe needs — and the ease with which you deliver it — can feel like a gift, though it may bring expectations or pressure to perform. Practically, this shows up in advocating for shared resources, mediating needs, or shaping what others accept as valuable. Tensions can arise when persuasion tips into manipulation or when you overextend. Aim for integrity, clear boundaries, and messages aligned with lasting community welfare rather than short-term approval." to "Предаване (26–44): Племенният канал на предавателя. Имате естествена склонност да предлагате, убеждавате и комуникирате онова, което общността смята за важно. Инстинктът ви за това, от което „племето“ се нуждае, и чарът ви в това да го предоставите често изглеждат като дар — но могат и да предизвикат очаквания или натиск да представяте стойност дори когато не е подходящо. Практическото приложение може да е в защитаване на ресурси, посредничество в конфликти или изграждане на доверие чрез прозрачност. Балансът идва от честност, ясни граници и избор на послания, които обслужват общото благо, а не само личната репутация."
        map[key(27,50)] = "Preservation (27–50): The channel of care and values. You are often finely tuned to what nourishes and preserves life — whether material resources, cultural heritage, or relational structures. The instinct to care for people, animals, or shared values can feel like a calling, but it may also lead to over-responsibility or protective rigidity. Practically, this channel shows in creating sustainable systems, stewarding traditions, or tending to others’ needs in daily life. For long-term effectiveness, practice setting boundaries, delegating when appropriate, and treating self-care as part of your stewardship rather than a luxury." to "Съхранение (27–50): Каналът на грижата и ценностите. Често сте дълбоко настроени към онова, което подхранва и запазва живота — материални ресурси, традиции или съпричастни взаимоотношения. Импулсът да се грижите за хора, животни и културни ценности носи усещане за мисия, но може да доведе и до пренебрегване на личните нужди или прекомерна защита. Практически това може да означава организиране на устойчиви системи, опазване на наследство или ежедневни грижи. За устойчив принос е полезно да установите граници, да делегирате и да интегрирате грижа за себе си като част от грижата за другите."
        map[key(28,38)] = "Struggle (28–38): The channel of purposeful struggle. You often feel driven to stand up for what has meaning and value; life can seem like a series of battles, but these struggles tend to be purposeful and revealing. This channel pushes you to test ideas, challenge complacency, and clarify what matters. Tensions may include being misunderstood, attracting resistance, or exhausting yourself on fights that aren’t yours. A constructive approach is to choose battles selectively, clarify your motives, build alliances, and balance persistence with rest so your efforts cultivate lasting value rather than burnout." to "Борба (28–38): Каналът на целенасочената борба. Често усещате натиск да отстоявате онова, което има смисъл и стойност за вас. Животът може да се усеща като постоянна борба, но тази е насочена и разкрива кои каузи заслужават усилията. Възможни са конфронтации и недоразумения — понякога борбата идва от нуждата да заявите стойностите си пред други, които не ги разбират. Полезно е да избирате битките си съзнателно, да запазвате вътрешна цел и да търсите стратегически съюзи, така че усилията ви да водят към устойчиви резултати, а не само към изтощение."
        map[key(29,46)] = "Discovery (29–46): The channel of commitment and love for embodiment. You often have sacral energy that enables deep commitment to people, projects, and experiences. Through wholehearted engagement you can discover the pleasures and lessons of being embodied — a visceral sense of aliveness. Commitment brings depth but can also create attachment or over-extension if chosen carelessly. Practice selective ‘yeses,’ maintain boundaries, and use simple rituals to stay connected to your body’s signals. When aligned, this channel helps you inhabit life richly and teach others the value of devoted presence." to "Откритие (29–46): Каналът на предаността и любовта към тялото. Често разполагате със сакрална енергия да се посветите дълбоко на хора, проекти и преживявания. Чрез ангажирано участие може да откриете радостта от съществуването в тяло и да развиете дълбока връзка с настоящия момент. Възможно е да се чувствате призовани да поемате обещания, което носи радост, но и риск от привързаност, когато ангажиментите не са внимателно избрани. Полезно е да избирате посветеността си съзнателно, да следите за граници и да поддържате ритуали, които подкрепят телесната ви наличност и удоволствие."
        map[key(30,41)] = "Recognition (30–41): The channel of fantasy and desire. You often feel a pressure to experience new emotions and situations; desire and the image of what could be fuel your curiosity and drive. This brings imagination, creative risk-taking, and the impulse to explore, but it can also lead to restlessness or an endless search for novelty. Channel your yearning into projects that translate imagination into tangible steps, and practice emotional integration so experiences deepen rather than fragment you. When desire is paired with discipline, it can produce innovative contributions and meaningful personal growth." to "Признание (30–41): Каналът на фантазията и желанието. Често изпитвате натиск да търсите нови емоции и преживявания — движени сте от мечтата за това, което може да бъде. Това внушава творческа визия и готовност за риск, но може да предизвика и неспокойство или чувство за постоянно търсене. Полезно е да канализирате желанието си в проекти, които превръщат въображението в конкретни стъпки, и да работите с емоционално усвояване, за да интегрирате преживяванията. Когато желанието се съчетае с последователност, то ражда иновативни и смислени промени."
        map[key(32,54)] = "Transformation (32–54): The channel of driven ambition and evolution. You often feel a continual pressure to transform, rise, and realize potential. You have an instinct for what will endure and flourish over time, which guides ambitious, upward movement. That drive can produce resilience and achievement, but it may also invite competitiveness, impatience, or burnout if unchecked. Practical strategies include long-term planning, honoring gradual skill development, seeking mentorship, and keeping ethical considerations central so your ascent supports lasting contribution rather than short-lived gain." to "Трансформация (32–54): Каналът на амбицията и преобразяването. Често усещате постоянен натиск да се трансформирате, да се изкачвате и да реализирате потенциал. Имате усет кои идеи, умения или ресурси ще оцелеят и ще се развият с времето, и това ви насочва към целенасочено движение нагоре. В същото време драйвът за успех може да носи съревнование, напрежение или риск от прегаряне. Практически подходи включват дългосрочно планиране, почитане на процеса на учене, търсене на наставничество и интегриране на етична перспектива, за да растежът бъде устойчив и смислен."
        map[key(34,57)] = "Power (34–57): An integration channel of instinctive survival energy. You often have potent sacral energy guided by splenic intuition — a near-instant bodily sense of what is safe or healthy. That somatic knowing gives you the capacity for quick, decisive action, which can be a major resource in crises or practical tasks. At the same time it may prompt impulsive moves if not reflected on. Use bodily signals as an important guide, cultivate the skill of distinguishing true intuition from fear, and build structures that channel your power into sustainable protection and practical care rather than reactive aggression." to "Сила (34–57): Интеграционен канал. Това е чиста сила за оцеляване, подтиквана от интуиция. Често имате изключително мощна сакрална енергия, насочвана от спленичната, интуитивна чувствителност: тялото ви може да „знае“ мигновено кое е безопасно и кое — не. Тази непосредствена мъдрост ви дава способността да действате бързо и решително, но може да доведе и до импулсивни решения, ако интуицията не се проверява. Практически ползвайте телесните сигнали като ценен ориентир, развивайте различаване между страх и интуиция и създавайте структури, които канализират силата ви в дългосрочно оцеляване и грижа."
        map[key(35,36)] = "Transitoriness (35–36): The channel of emotional experience. You are often driven to seek varied human experiences — the full range of what it means to be alive. Your emotional depth expands by living through many situations and relationships, but that appetite for novelty can create instability in commitments or repeated experimentation in close ties. For steadiness, allow time to integrate experiences, practice emotional regulation, and confide in trusted others. When processed consciously, your breadth of feeling becomes a resource for insight and empathy rather than a source of repeated turmoil." to "Преходност (35–36): Каналът на емоционалното преживяване. Често ви движи стремежът да търсите разнообразни човешки преживявания — пълния спектър на това да бъдеш жив. Емоционалната ви дълбочина расте чрез участие в различни ситуации и връзки, но това може да доведе до нестабилност на ангажиментите или повторни експерименти в личните отношения. За вътрешно равновесие е полезно да оставите време за интеграция между преживяванията, да практикувате емоционално овладяване и да споделяте процеса си с доверени хора. Това позволява богатата емоционална палитра да стане източник на растеж, а не само на хаос."
        map[key(37,40)] = "Community (37-40): The tribal channel of bargaining and belonging. You often have a talent for forming and sustaining communities through clear agreements, mutual support and shared protocols. This can make you a natural mediator and organizer — able to steer groups toward clarity and loyalty while still acknowledging individual needs. Tensions may arise around expectations or dependency, so boundaries and transparent arrangements are helpful to avoid burnout. Practical guidance: set explicit roles and agreements, encourage reciprocity and accountability, and allow space for personal autonomy within the group to keep bonds healthy and resilient." to "Общност (37-40): Племенният канал на договарянето и изграждането на принадлежност. Често имате дара да създаваш и поддържаш общности чрез ясни договорки, ритуали на подкрепа и взаимност. Това те прави естествен медиатор и организатор — можете да насочваш групите към яснота и лоялност, като същевременно уважаваш индивидуалните нужди. Възможни са напрежения около очакванията и зависимостите: важно е да поставяш граници и да формализираш споразумения, за да предотвратиш изтощение. Практически съвет: оформяй ясни правила и роли, поощрявай отчетността и оставяй място за автономност в рамките на общността."
        map[key(39,55)] = "Emoting (39-55): The channel of individual emotional provocation. Your energy often stirs others’ feelings in ways that can help them access passion, clarity or renewed motivation. This capacity can be both catalytic and unsettling: it can catalyze growth, yet provoke strong reactions. Timing, consent and emotional awareness matter — well-timed provocation can open doors to insight, while impulsive pushes may be perceived as manipulative. Practical guidance: cultivate emotional regulation, check in with others before intense interventions, and use your prompting energy to inspire authentic expression and healing rather than control." to "Емотиране (39-55): Каналът на индивидуалната емоционална провокация. Твоята енергия често предизвиква и разтърсва емоциите на другите, подпомагайки ги да открият своята страст, истина или мобилизация. Това може да бъде лечебно и пробуждащо, но и дразнещо — хората понякога реагират интензивно. Важно е да разпознаваш границите и времето: провокацията, направена с уважение и ясно намерение, може да доведе до прозрения; ако е импулсивна, рискува да се тълкува като манипулация. Съвет: практикувай емоционална осъзнатост, търси съгласие при силни интервенции и използвай енергията си за вдъхновение и изцеление."
        map[key(42,53)] = "Maturation (42-53): The channel of life cycles and completion. You often feel a strong drive to initiate new phases and — crucially — to bring them to full completion. Each cycle offers lessons, growth and a sense of closure; when endings are avoided, lessons may repeat or remain unresolved. You may face impatience or a fear of loss around conclusions, so intentional transition practices and rites of passage are useful. Practical guidance: structure projects and relationships in phases, allow time for integration after endings, and treat closures as opportunities for learning and renewal rather than mere termination." to "Зреене (42-53): Каналът на жизнените цикли и завършването. Често усещаш силен натиск да започваш нови цикли и — още по-важно — да ги завършваш с внимание. Всеки цикъл носи уроци, растеж и усещане за завършеност, но без финал може да остане неизчистена карма или недовършено учене. Може да се бориш с нетърпение или страх от загуба, когато предстои край; практиката на ритуали на преход и ясни крачки към завършване помага. Съвет: планирай фази, отдавай време за интеграция след края и намирай смисъл в преходите, за да превърнеш всяко приключване в източник на мъдрост."
        map[key(47,64)] = "Abstraction (47-64): The channel of mental abstraction and making sense of the past. You are often driven to detect patterns and to transform confusing or fragmented experiences into generalized insight. This tends to involve an intuitive grasp of recurring themes and the formulation of ideas that make personal or collective histories more coherent. The downside can be detachment from concrete detail or an overreliance on theory. Practical guidance: test your hypotheses in real situations, present your insights with humility, and balance abstract thinking with empathetic listening so your interpretations remain grounded and useful." to "Абстракция (47-64): Каналът на менталната абстракция и осмислянето на миналото. Мотивиран си да откриваш модели и да превръщаш объркващи или фрагментарни преживявания в обобщена мъдрост. Този процес често включва интуитивно улавяне на повтарящи се теми и формулиране на теории, които придават смисъл на личната или колективната история. Рискът е да се отдалечиш от конкретността или да се съсредоточиш върху идеите в ущърб на емпатията. Съвет: тестирай своите хипотези на практика, споделяй прозренията си с уважение и балансирай абстрактното мислене с внимателно слушане."

        map.toMap()
    }

    private fun channelKey(ch: HdChannel) = "${minOf(ch.a, ch.b)}-${maxOf(ch.a, ch.b)}"

    fun channelDescriptionFor(ch: HdChannel): Pair<String, String>? = channelInfo[channelKey(ch)]

    fun profileKey(personalityLine: Int, designLine: Int) = "$personalityLine/$designLine"
}
