package eu.kastroguru.astrodiary.domain.humandesign

/**
 * Open (undefined) centres read as conditioning rather than as description.
 *
 * `HdDescriptions.centerInfo[c].undefined` already says what an open centre *is*. This object says
 * what it *does to you*: the false question it makes you chase, and the correction. Consultations
 * spend most of their time here, because this is the layer that explains the pressure a person
 * walked in with.
 *
 * Each entry: the false question, then what it costs, then what to do instead. EN to BG.
 */
object HdOpenCenterTexts {

    val conditioning: Map<HdCenter, Pair<String, String>> = mapOf(

        HdCenter.HEAD to (
            "The false question here is \"whose question am I actually trying to answer?\" With this centre open you pick up mental pressure from everyone around you and treat it as your own homework — puzzles that were never yours to solve, inspiration you feel obliged to act on. The cost is a head that never switches off and a lot of energy spent on questions that make no difference to your life. The correction is small and repeatable: when a question starts spinning, ask where it came from, and let go of the ones you cannot trace back to yourself. Your mind is built to be inspired by many things and to answer almost none of them."
                    to "Фалшивият въпрос тук е „чий въпрос всъщност се опитвам да отговоря?“. С отворен център поемате мисловния натиск на всички около вас и го приемате за своя домашна работа — гатанки, които никога не са били ваши, вдъхновения, по които се чувствате длъжни да действате. Цената е глава, която не се изключва, и много енергия, изхабена по въпроси, които не променят нищо в живота ви. Поправката е малка и се повтаря: когато един въпрос започне да се върти, попитайте откъде е дошъл и пуснете онези, които не можете да проследите до себе си. Умът ви е направен да се вдъхновява от много неща и да отговаря на почти нито едно."),

        HdCenter.AJNA to (
            "The false question is \"how do I look like I know?\" An open Ajna gives you a mind that can hold any framework and try on any opinion, but it also makes you afraid of being caught not knowing, so you state things more firmly than you feel them. The cost is that you defend positions you do not actually hold, and lose the flexibility that is your real advantage. Try saying \"I don't know yet\" out loud and noticing that nothing bad happens. Certainty is not your job; being able to think in someone else's system and then step out of it again is."
                    to "Фалшивият въпрос е „как да изглеждам, че знам?“. Отворената Аджна ви дава ум, който може да поеме всяка рамка и да пробва всяко мнение, но също ви прави да се страхувате да бъдете хванати в незнание — затова изричате неща по-твърдо, отколкото ги чувствате. Цената е, че защитавате позиции, които всъщност не държите, и губите гъвкавостта, която е истинското ви предимство. Опитайте да казвате „още не знам“ на глас и вижте, че нищо лошо не се случва. Сигурността не е вашата работа; способността да мислите в чужда система и после да излезете от нея — това е."),

        HdCenter.THROAT to (
            "The false question is \"how do I get them to notice me?\" With the throat open you feel a pull to speak or do something in order to be seen, and you often talk before there is anything to say. The cost is interrupting, filling silences, and taking on work simply because saying yes got you attention. What works instead is waiting until you are actually asked — and you will be, more often than you expect, because an open throat makes people curious about what you are quietly thinking. Attention that arrives on its own is worth ten times the attention you went out and fetched."
                    to "Фалшивият въпрос е „как да ме забележат?“. С отворено гърло усещате тегленето да кажете или да направите нещо, за да бъдете видени, и често говорите преди да има какво да се каже. Цената е прекъсване, запълване на тишината и поемане на работа само защото едно „да“ ви е донесло внимание. Работи обратното: изчакайте наистина да ви попитат — и това ще се случва по-често, отколкото очаквате, защото отвореното гърло прави хората любопитни какво мислите, докато мълчите. Вниманието, което дойде само, струва десет пъти повече от онова, което сте отишли да си вземете."),

        HdCenter.G to (
            "The false question is \"who am I and where am I going?\" — and it is false because you are not built to carry an answer around inside you. With the G centre open, both your sense of self and your direction arrive through the place you are in and the people you are with, and they change when those change. The cost is years spent looking for a fixed identity and judging yourself for not having one. The practical move is to stop working on who you are and start being careful about where you are: the right room and the right company give you a direction you could not think your way to. Notice which places make you feel like yourself, and go back to them."
                    to "Фалшивият въпрос е „кой съм аз и накъде отивам?“ — и е фалшив, защото не сте направени да носите отговора вътре в себе си. С отворен G център и усещането за себе си, и посоката ви идват през мястото, на което сте, и хората, с които сте, и се променят, когато те се променят. Цената са години в търсене на постоянна самоличност и самоосъждане, че я няма. Практичната стъпка е да спрете да работите върху това кой сте и да започнете да внимавате къде сте: правилната стая и правилната компания ви дават посока, до която не бихте стигнали с мислене. Забелязвайте кои места ви връщат при себе си и се връщайте при тях."),

        HdCenter.HEART to (
            "The false question is \"how do I prove I'm worth it?\" An open Heart makes willpower come and go, so in the moments when it is present you promise things — and then the energy leaves and the promise stands there without you. The cost is a slow accumulation of broken commitments, each one adding to the feeling that you have to prove yourself all over again. There is nothing to prove; your worth is not a debt. Commit in short pieces, say plainly that you cannot guarantee more, and let the results speak instead of the promises."
                    to "Фалшивият въпрос е „как да докажа, че струвам?“. Отвореното Сърце прави волята да идва и да си отива, така че в моментите, когато я има, обещавате — а после енергията си тръгва и обещанието остава да стои без вас. Цената е бавно натрупване на неудържани ангажименти, всеки от които добавя към чувството, че трябва отново да се доказвате. Няма какво да доказвате; стойността ви не е дълг. Поемайте кратки ангажименти, казвайте открито, че не можете да гарантирате повече, и оставяйте резултатът да говори вместо обещанието."),

        HdCenter.SACRAL to (
            "The false question is \"why can't I keep up?\" With no sacral definition you do not have your own supply of work energy — you borrow it from whoever is around, which is why you can go all day in the right company and collapse alone in the evening. The cost is enormous, because you learn early that you can push, and you keep pushing until something in the body stops you. The correction is unpopular and it works: lie down before you are tired, not after. Rest is not a reward you earn at the end of the day; for you it is the thing that makes the day possible."
                    to "Фалшивият въпрос е „защо не смогвам?“. Без сакрална дефиниция нямате собствен запас от работна енергия — заемате го от онези, които са наоколо, и точно затова можете да изкарате цял ден в правилната компания и да се сринете сами вечерта. Цената е огромна, защото рано научавате, че можете да се насилвате, и продължавате, докато нещо в тялото не ви спре. Поправката е непопулярна и работи: лягайте, преди да сте изморени, а не след това. Почивката не е награда, която заслужавате в края на деня; за вас тя е онова, което прави деня възможен."),

        HdCenter.SPLEEN to (
            "The false question is \"what if I let go and something bad happens?\" An open Spleen has no steady alarm system of its own, so it holds on — to jobs, to people, to habits — long after they stopped being good, because the fear of letting go is louder than the discomfort of staying. The cost is years of clinging, plus a tendency to collect health worries that belong to other people. What helps is naming the fear as fear rather than as information, and noticing that almost everything you eventually did let go of, you were relieved to be rid of. Your body does give you signals; they are just quieter than the panic."
                    to "Фалшивият въпрос е „а ако пусна и стане нещо лошо?“. Отворената Слезка няма своя постоянна алармена система, затова се държи — за работа, за хора, за навици — дълго след като са спрели да са добри, защото страхът да пуснете е по-силен от неудобството да останете. Цената са години вкопчване плюс склонност да събирате здравни тревоги, които са на други хора. Помага да наречете страха страх, а не информация, и да забележите, че почти всичко, което накрая сте пуснали, ви е донесло облекчение. Тялото ви дава сигнали; те просто са по-тихи от паниката."),

        HdCenter.SOLAR_PLEXUS to (
            "The false question is \"how do I keep the peace?\" With this centre open you feel other people's emotional weather as if it were your own, and you learn to smooth things over — avoiding the honest sentence, agreeing early, leaving the difficult thing unsaid so nobody's mood turns. The cost is a life arranged around other people's comfort and a lot of resentment with nowhere to go. The correction is to check whose feeling it is before you act on it; step out of the room and see whether it goes with you. Most of what you feel in company is not yours, and the truth you keep swallowing is the one thing worth saying."
                    to "Фалшивият въпрос е „как да опазя мира?“. С отворен център усещате емоционалното време на другите като свое и се научавате да заглаждате — избягвате честното изречение, съгласявате се рано, оставяте трудното неказано, за да не се обърне настроението на някого. Цената е живот, подреден около удобството на другите, и много обида, която няма къде да отиде. Поправката е да проверите чие е чувството, преди да действате по него: излезте от стаята и вижте дали идва с вас. Повечето от онова, което чувствате в компания, не е ваше, а истината, която непрекъснато преглъщате, е единственото, което си струва да се каже."),

        HdCenter.ROOT to (
            "The false question is \"if I just get this done, will the pressure stop?\" It will not — an open Root turns every task into urgency, and the moment one thing is finished the next takes its place, so you live in a permanent hurry that has nothing to do with real deadlines. The cost is rushed work, decisions made to be rid of the discomfort, and a body that never fully unclenches. What helps is separating pressure from timing: let the pressure sit there, unresolved, while you do the thing at the speed it actually needs. You are not late. You are being pushed by an energy that is not yours, and it will keep pushing whether or not you obey it."
                    to "Фалшивият въпрос е „ако само свърша това, ще спре ли натискът?“. Няма да спре — отвореният Корен превръща всяка задача в спешност и в момента, в който едно нещо приключи, следващото заема мястото му, така че живеете в постоянно бързане, което няма нищо общо с истинските срокове. Цената е претупана работа, решения, взети само за да се отървете от неудобството, и тяло, което никога не се отпуска докрай. Помага да разделите натиска от времето: оставете натиска да си стои неразрешен, докато вършите нещото със скоростта, която наистина му е нужна. Не сте закъснели. Бута ви енергия, която не е ваша, и ще бута независимо дали ѝ се подчинявате."))
}
