package eu.kastroguru.astrodiary.domain.humandesign

/**
 * The child's chart read as instructions for the parent — type crossed with authority.
 *
 * Only 13 combinations can exist: a Generator or Manifesting Generator has a defined Sacral, so
 * its authority is Sacral or Emotional; a Manifestor has no Sacral, leaving Emotional, Splenic or
 * Ego; a Projector adds Self-Projected and Mental; a Reflector is always Lunar. [keyFor] builds
 * the key, and [parenting] has an entry for every combination the calculator can produce.
 *
 * The type says how to approach the child; the authority says how to ask a question and how long
 * to wait for the answer. Both halves are written as things a parent does, not as description.
 */
object HdParentingTexts {

    fun keyFor(type: HdType, authority: HdAuthority) = "${type.name}|${authority.name}"

    val parenting: Map<String, Pair<String, String>> = mapOf(

        keyFor(HdType.GENERATOR, HdAuthority.SACRAL) to (
            "Ask this child closed questions and listen to the sound before the words: \"do you want to go?\" gets you a real answer, \"what do you want to do?\" gets you a made-up one. The uh-huh or uh-uh that comes out of the belly is the decision, and it is available immediately — there is no waiting with a sacral child, but there is also no arguing with it. What breaks a Generator child is being made to keep going at something the body has stopped saying yes to; frustration is the signal, not bad behaviour. Give them plenty to respond to, let them refuse without a debate, and protect their sleep — they need to be in bed before the energy is spent."
                    to "Задавайте на това дете затворени въпроси и слушайте звука преди думите: „искаш ли да отидем?“ носи истински отговор, „какво искаш да правиш?“ носи измислен. Онова „ъхъ“ или „ъ-ъ“, което излиза от корема, е решението, и то е налично веднага — при сакрално дете няма чакане, но няма и спорене с него. Генераторното дете се пречупва, когато го карат да продължава нещо, на което тялото вече е спряло да казва „да“; фрустрацията е сигнал, не непослушание. Давайте им много неща, на които да отговорят, оставяйте ги да откажат без дебат и пазете съня им — трябва да са в леглото, преди енергията да е свършила."),

        keyFor(HdType.GENERATOR, HdAuthority.EMOTIONAL) to (
            "This child has the energy of a Generator and the timing of an emotional wave, which means the first answer is never the answer. Ask closed questions — \"do you want to?\" — but then say out loud that they can tell you tomorrow, and mean it. Their mood will swing without a reason you can find, and the mistake most parents make is treating the low point as a problem to fix or the high point as a promise to hold them to. Neither is true; both are weather. Let them change their mind without shame, decide important things after a night's sleep, and do not force an answer while they are still up or still down."
                    to "Това дете има енергията на генератор и времето на емоционална вълна — значи първият отговор никога не е отговорът. Задавайте затворени въпроси — „искаш ли?“ — но след това кажете на глас, че могат да ви кажат утре, и наистина го спазвайте. Настроението им ще се качва и слиза без причина, която можете да откриете, и грешката на повечето родители е да приемат ниската точка за проблем, който трябва да се реши, или високата за обещание, което трябва да се удържи. И двете са грешни; и двете са време. Оставяйте ги да си променят решението без вина, решавайте важните неща след нощ сън и не изтръгвайте отговор, докато вълната още се движи."),

        keyFor(HdType.MANIFESTING_GENERATOR, HdAuthority.SACRAL) to (
            "Expect this child to do four things at once and to leave three of them unfinished, and expect that to be correct rather than lazy. Ask closed questions and trust the gut sound; it will often say yes to starting and, halfway through, plainly stop saying yes — that is the design working, not a failure of character. The one habit worth teaching early is informing: before you dash off, tell the people who were part of it. Without that they meet resistance everywhere and cannot understand why, and they get labelled as unreliable by adults who were simply never told."
                    to "Очаквайте това дете да прави четири неща наведнъж и да остави три недовършени, и очаквайте това да е правилно, а не лениво. Задавайте затворени въпроси и се доверявайте на звука от корема; той често ще каже „да“ на започването и по средата просто ще спре да казва „да“ — това е дизайнът, който работи, а не слабост на характера. Единственият навик, който си струва да се учи рано, е информирането: „преди да хукнеш, кажи на хората, които са били част от това“. Без него срещат съпротива навсякъде и не разбират защо, а възрастните ги наричат ненадеждни само защото не са били предупредени."),

        keyFor(HdType.MANIFESTING_GENERATOR, HdAuthority.EMOTIONAL) to (
            "Fast energy on a slow clock — this child wants to start now and cannot know now whether it is right. The job of the parent is to buy them time without shaming the impulse: \"yes, and let's decide tomorrow\" rather than \"calm down\". They will start things at the top of the wave and abandon them at the bottom, so help them tell the difference between a thing that has finished and a thing they are only tired of. Teach informing at the same time, because they move before they speak and then wonder why everyone is annoyed. Their anger and frustration together are not a discipline problem; they are the two signals that the timing was skipped."
                    to "Бърза енергия на бавен часовник — това дете иска да започне сега и не може да знае сега дали е правилно. Работата на родителя е да им купи време, без да засрамва импулса: „да, и ще решим утре“, вместо „успокой се“. Ще започват неща на върха на вълната и ще ги зарязват на дъното, затова им помагайте да различават нещо, което е приключило, от нещо, от което просто са се изморили. Учете ги и на информиране, защото се движат, преди да говорят, и после се чудят защо всички са им сърдити. Гневът и фрустрацията заедно не са проблем с дисциплината; те са двата сигнала, че времето е било прескочено."),

        keyFor(HdType.MANIFESTOR, HdAuthority.EMOTIONAL) to (
            "This child is here to start things, and the single most damaging question you can ask is \"what are you doing?\" — it lands as a block, and a blocked Manifestor child either goes quiet for years or fights everything. Replace control with informing, in both directions: you tell them before you change their plans, and you teach them to tell you before they change yours. Their authority is a wave, so the answer to anything important is not available today; give them the night. Anger will come out when they are interrupted mid-initiation — treat it as information about your timing rather than a character flaw."
                    to "Това дете е тук да започва неща, и най-вредният въпрос, който можете да зададете, е „какво правиш?“ — той се приема като блокиране, а блокираното манифесторно дете или замлъква за години, или се бие с всичко. Заменете контрола с информиране, и в двете посоки: вие им казвате, преди да промените плановете им, и ги учите да казват, преди да променят вашите. Авторитетът им е вълна, така че отговорът на важно нещо не е наличен днес; дайте им нощта. Гневът ще излиза, когато ги прекъснат по средата на започването — приемайте го като информация за вашето време, а не като дефект в характера."),

        keyFor(HdType.MANIFESTOR, HdAuthority.SPLENIC) to (
            "A Manifestor child with splenic authority decides in an instant and only once. If they say no to the water, the food, the person — the first time is the whole answer, and asking again five minutes later gets you a made-up reply from the mind instead. This is the child whose instinct about a place or a stranger is worth more than your reasoning, so take it seriously in front of them. Teach informing, keep out of the way of what they start, and understand that their anger is what happens when they are stopped, not when they are unhappy with you. Sudden and quiet is how they work; slow explanations do not reach them."
                    to "Манифесторно дете със спленичен авторитет решава в един миг и само веднъж. Ако кажат „не“ на водата, на храната, на човека — първият път е целият отговор, а ако попитате отново след пет минути, ще получите измислен отговор от ума. Това е детето, чийто инстинкт за място или за непознат струва повече от вашите разсъждения, затова го приемайте сериозно пред него. Учете го да информира, не му пречете на започнатото и разберете, че гневът им е онова, което се случва, когато ги спрат, а не когато са недоволни от вас. Работят внезапно и тихо; бавните обяснения не ги стигат."),

        keyFor(HdType.MANIFESTOR, HdAuthority.EGO) to (
            "This child decides from the heart in the plainest sense: what do I want, and is it worth my will? Ask them directly whether they want it — not whether they should — and take the answer at face value, because a want that is real in them is reliable and a want that has been talked into them collapses. Do not use their promises as leverage; their will is genuinely strong but it is theirs to spend, and being made to prove it is what turns a capable child into a resentful one. Informing still applies, and so does staying out of the way once they have begun."
                    to "Това дете решава от сърцето в най-простия смисъл: какво искам и струва ли си волята ми? Питайте директно дали го искат — не дали трябва — и приемайте отговора буквално, защото желание, което е истинско в тях, е надеждно, а желание, което им е внушено, се разпада. Не използвайте обещанията им като лост; волята им наистина е силна, но е тяхна да я изразходват, и точно принудата да я доказват превръща способното дете в озлобено. Информирането пак важи, както и да не им се пречи, след като са започнали."),

        keyFor(HdType.PROJECTOR, HdAuthority.EMOTIONAL) to (
            "This child sees things about people that a child should not be able to see, and says them out loud — and then gets punished for it, which is how a Projector learns to stop speaking. Wait to be invited into what they are doing, ask instead of directing, and recognise them by name for what they noticed rather than for how much they achieved. They do not have Generator energy: an afternoon of activities that another child would enjoy leaves them flattened, and lying down before they are tired is not laziness. With an emotional wave on top, no important answer is available today — give it a night and let them change their mind in the morning."
                    to "Това дете вижда неща за хората, които дете не би трябвало да може да види, и ги казва на глас — и после бива наказано за това, така проекторът се научава да спре да говори. Изчаквайте да ви поканят в онова, което правят, питайте, вместо да нареждате, и ги признавайте по име за онова, което са забелязали, а не за това колко са свършили. Нямат генераторна енергия: следобед с активности, който друго дете би харесало, ги оставя изцедени, а да легнат, преди да са изморени, не е леност. С емоционална вълна отгоре, никакъв важен отговор не е наличен днес — дайте му нощ и ги оставете да променят решението си сутрин."),

        keyFor(HdType.PROJECTOR, HdAuthority.SPLENIC) to (
            "Sharp eyes and a one-time instinct: this child knows in the first second whether a place or a person is right, and cannot reproduce that knowing on demand. Ask once, believe the first answer, and never interrogate them into a second one. Recognition is what they live on — being seen for what they noticed, invited rather than instructed — and bitterness is what grows when they are overlooked or pushed. Guard their energy carefully: they will keep up with the other children until they suddenly cannot, so build rest into the day before it is needed rather than after."
                    to "Остри очи и еднократен инстинкт: това дете знае в първата секунда дали едно място или човек е правилен, и не може да възпроизведе това знание по заявка. Питайте веднъж, вярвайте на първия отговор и никога не ги разпитвайте до втори. Живеят от признание — да бъдат видени за онова, което са забелязали, поканени, а не инструктирани — а горчивината расте, когато ги подминават или бутат. Пазете енергията им внимателно: ще догонват другите деца, докато внезапно спрат да могат, затова слагайте почивка в деня, преди да е нужна, а не след това."),

        keyFor(HdType.PROJECTOR, HdAuthority.EGO) to (
            "With this child the useful question is always \"do you want to?\", and the answer is binding in both directions — if the want is not there, no amount of reasoning will produce the follow-through, and if it is there, the will is surprisingly durable. Their gift is seeing how other people work, and it needs an invitation to come out; unasked advice from a Projector child gets read as cheek. Recognise them out loud, invite them in, and do not turn their promises into a test of character. They tire in a way that looks like reluctance and is not — rest early, and often."
                    to "При това дете полезният въпрос винаги е „искаш ли?“, и отговорът е обвързващ в двете посоки — ако желанието го няма, никакви доводи няма да произведат довеждане до край, а ако го има, волята е изненадващо издръжлива. Дарбата им е да виждат как работят другите хора и тя има нужда от покана, за да излезе; несподелен съвет от проекторно дете се приема за нахалство. Признавайте ги на глас, канете ги и не превръщайте обещанията им в изпит по характер. Изморяват се по начин, който изглежда като неохота и не е — почивка рано и често."),

        keyFor(HdType.PROJECTOR, HdAuthority.SELF_PROJECTED) to (
            "This child finds the answer by hearing themselves say it. Your job is to be the person they can talk at without being advised: let them think out loud about the choice, and listen to the voice rather than the argument — it lifts on the right answer and goes flat on the wrong one, often while the words say the opposite. Do not give your opinion until they have finished; one adult verdict too early and the whole process closes down. They also need direction from outside, which means the place and the company matter more than the plan, and identity questions have no answer you can help them think their way to."
                    to "Това дете намира отговора, като се чуе да го казва. Вашата работа е да сте човекът, на когото могат да говорят, без да ги съветват: оставяйте ги да мислят на глас за избора и слушайте гласа, не аргумента — той се повдига при правилния отговор и се снишава при грешния, често докато думите казват обратното. Не давайте мнението си, докато не свършат; една присъда от възрастен, дадена рано, затваря целия процес. Имат нужда и от посока отвън — значи мястото и компанията са по-важни от плана, а въпросите за самоличността нямат отговор, до който можете да им помогнете да стигнат с мислене."),

        keyFor(HdType.PROJECTOR, HdAuthority.MENTAL) to (
            "Everything about this child is open, so almost everything they feel and think arrives from outside — and they will present borrowed certainty as their own. There is no inner authority to consult, which sounds alarming and is not: their guidance is the environment. Take seriously where they sleep, which school, whose house they spend afternoons in, because those choices decide far more than any conversation will. Let them talk things through with several trusted people and treat the talking as data-gathering, never as a vote. Recognition and rest still rule the day, and the wrong room will exhaust them faster than any amount of work."
                    to "Всичко в това дете е отворено, така че почти всичко, което чувства и мисли, идва отвън — и ще ви поднася заета сигурност като своя. Няма вътрешен авторитет за консултация, което звучи тревожно, а не е: тяхната насока е средата. Приемайте сериозно къде спят, кое училище, в чия къща прекарват следобедите, защото тези избори решават много повече от всеки разговор. Оставяйте ги да обсъждат с няколко доверени хора и приемайте говоренето като събиране на данни, никога като гласуване. Признанието и почивката пак управляват деня, а грешната стая ще ги изтощи по-бързо от всякаква работа."),

        keyFor(HdType.REFLECTOR, HdAuthority.LUNAR) to (
            "This child is a mirror, and what it mirrors is your household. On a good week they seem like a different person from a bad week, and the difference is usually not in them — it is in who has been around and what the room has felt like. Nothing important should be decided quickly; give a big choice most of a month and watch how it looks at different points, because their clarity comes from time passing rather than from a feeling in the body. Choose their company with more care than their activities, protect long stretches of being left alone, and never ask them to be consistent. Disappointment is the sign that they have been rushed or kept somewhere that does not suit them."
                    to "Това дете е огледало и онова, което отразява, е вашият дом. В добра седмица изглежда като различен човек от лоша седмица, и разликата обикновено не е в него — тя е в това кой е бил наоколо и как се е усещала стаята. Нищо важно не бива да се решава бързо; дайте на голям избор почти месец и гледайте как изглежда в различни моменти, защото яснотата им идва от изминалото време, а не от усещане в тялото. Подбирайте компанията им по-внимателно от занятията, пазете им дълги периоди да бъдат оставени сами и никога не искайте от тях последователност. Разочарованието е знакът, че са били припирани или държани там, където не им е добре."))
}
