package eu.kastroguru.astrodiary.domain.interpretation.written

import eu.kastroguru.astrodiary.domain.interpretation.Bilingual

/**
 * Hand-written Ascendant-in-sign texts: the first impression, and the way someone opens a situation.
 * The third placement people read, and the one that most often explains why someone is described by
 * others in a way that does not match how they feel inside.
 */
object AscendantInSign {

    private fun t(en: String, bg: String) = Bilingual(en, bg)

    val entries: Map<String, Bilingual> = mapOf(
        "asc_aries" to t(
            "You present as direct, quick and ready to take the lead, so others often expect you to initiate. You meet new situations head-on rather than study them, which reads as confidence even when you feel uncertain. Your drive is ideal for starting projects, yet it can produce hasty choices or friction. Practical advice: pause briefly before acting, direct your energy toward deliberate beginnings, and cultivate patience with moments of inner doubt.",
            "Проявявате се пред света като директен, бърз и импулсивен човек — околните често очакват да поемете инициативата. Новите ситуации срещате напред, вместо да ги анализирате, и това често се чете като увереност, дори когато вътрешно не сте сигурни. Силната ви енергия е ценна за започване на проекти, но може да доведе до прибързани решения или конфликти. Насоки: огледайте импулса преди действие, канализирайте енергията в ясни начала и практикувайте търпение към собствените несигурности."
        ),
        "asc_taurus" to t(
            "You come across as steady, unhurried and reliable, someone unlikely to be rushed. That calm quickly earns trust but can mask how much activity is happening beneath the surface. You value comfort, sensory pleasure and durable relationships; sudden change can drain you. Practical tips: use your steadiness to build consistency, while practising flexibility and sharing the inner work you’re doing so people appreciate the effort behind your composed exterior.",
            "Оставяте впечатление на уравновесен и ненатоварен човек, който не бърза и предпочита устойчивост. Това спокойствие кара хората да ви се доверяват бързо, но също така може да прикрива колко работи се извършват вътре. Цените комфорт, сетивност и стабилни връзки; промените ви изтощават, ако са твърде бързи. Практически съвет: използвайте устойчивото си темпо като ресурс за последователност, но се упражнявайте в адаптивност и комуникиране на вътрешните усилия."
        ),
        "asc_gemini" to t(
            "You arrive with talk, curiosity and quick connections—easy company and lively conversation. People may take you as lighter or more surface-level because you prefer to be interesting rather than intense at first meetings. Your curiosity brings variety but can scatter your focus. Useful practices: pick a few topics for deeper follow‑through, cultivate active listening, and develop routines that help you finish what you start.",
            "Пристигате в света с разговор, въпроси и бързи връзки между идеи — лесни сте за компания и комуникация. Хората често ви приемат за по-лек или по-повърхностен, защото при първа среща предпочитате да впечатлявате и да бъдете интересни, а не дълбоки. Любознателността ви носи разнообразие, но и риск от разпиляване. Насоки: изберете няколко области за по-задълбочено внимание, упражнявайте активно слушане и работете върху последователност в проектите."
        ),
        "asc_cancer" to t(
            "You present as gentle, caring and attuned to others’ moods, often testing the waters before entering a new situation. Your first move is typically to gauge safety, and you value relationships that offer emotional security and depth. Protective instincts can come across as guardedness. Practical suggestions: develop rituals that make you feel secure, reveal vulnerability gradually, and allow others opportunities to demonstrate reliability in return.",
            "Проявявате се като мек, грижовен и наблюдателен човек, който усеща настроението на другите. Преди да влезете в нова ситуация, обикновено „пробвате водата“ и първото ви движение е да прецените дали е безопасно. Връзките ви търсят сигурност и емоционална дълбочина; понякога защитният ви механизъм може да изглежда резервиран или предпазлив. Практически подход: създайте ритуали за усещане на сигурност, споделяйте малко по малко уязвимостта си и позволете на хората да покажат сигурност обратно."
        ),
        "asc_leo" to t(
            "You tend to be noticed whether you seek it or not. Your presence feels warm, dramatic and slightly theatrical; people often expect you to carry the room. That attention can flatter and empower you, but it can also feel burdensome when you're tired or vulnerable. Key themes are a need for recognition, generosity and natural leadership; tensions appear when showmanship overrides authenticity. A helpful approach is to use the spotlight intentionally—for creativity or service—and to schedule rest and quieter ways to be seen.",
            "Забелязват ви — независимо дали търсите внимание или не. Вашето присъствие е топло, драматично и често носи усещане за сцена; хората очакват от вас да „носите стаята“. Това може да ви ласкае и да ви дава възможност да влияете позитивно, но и да тежи, когато сте уморени или уязвими. Темите включват нужда от признание, щедрост и стремеж към лидерство; практика е да насочвате вниманието си в смислени проекти и да си позволявате почивка, за да избегнете изтощение."
        ),
        "asc_virgo" to t(
            "You come across as capable, observant and practical—the person who notices the details and can organize things. You tend to assess new situations before committing, and your first instinct is to be useful rather than to be liked. This makes you a reliable colleague or friend, though it can slide into self-criticism or perceived reserve. Try making your intentions visible and allowing some softness in first impressions; small gestures of warmth help others see the person behind the competence.",
            "Излизате пред другите като способен, наблюдателен и практичен — човекът, който е забелязал детайлите и може да подреди нещата. Новите ситуации първо ги оценявате, преди да поемете ангажимент, а естественият ви импулс е да бъдете полезни. Това ви прави надежден съюзник, но понякога и прекалено критични — към себе си и към околните. Полезно е да практикувате ясно споделяне на намеренията и да позволявате малко повече широта и топлина в първите срещи."
        ),
        "asc_libra" to t(
            "You arrive as pleasant and accommodating, and people tend to relax around you. Your reflex is to smooth things over and seek harmony, which makes first meetings easy but can obscure what you really think. Themes include aesthetics, diplomacy and a strong sense of fairness; the tension is between keeping the peace and stating your needs. A constructive approach is to practice brief, clear expressions of preference and to set gentle boundaries so your charm doesn’t become a mask for avoidance.",
            "Пристигате приветливи и отзивчиви; хората се отпускат около вас. Рефлексът ви е да изглаждате напрежението и да търсите хармония, което прави първите срещи лесни и приятни. В същото време това може да затрудни другите да разберат какво наистина мислите, защото предпочитате компромиса пред директния спор. Темите включват естетика, дипломация и търсене на баланс; практическо насочване е да упражнявате кратки, ясни изказвания на предпочитания и граници, за да запазите честността във взаимоотношенията."
        ),
        "asc_scorpio" to t(
            "You give little away, and people notice that. You present as self-contained and watchful, with an intensity that draws some people in and keeps others at a distance. You tend to read motivations and undercurrents quickly, which can be an advantage but may also generate suspicion or power plays. Themes include depth, transformation and personal power; a constructive path is to reveal yourself in measured ways, channel intensity into focused work or healing, and practice honest boundaries to avoid manipulative dynamics.",
            "Давате малко от себе си и това се усеща. Излизате пред хората като самодостатъчни и наблюдателни, с интензивност, която привлече някои и държи други на разстояние. Често имате способността бързо да разбирате мотивации и скрити пластове в отношенията, което ви дава предимство, но може да роди подозрителност или контрол. Темите са дълбочина, трансформация и лична сила; полезно е стратегически да разкривате себе си поетапно и да канализирате интензивността към изцеление или фокусирана работа."
        ),
        "asc_sagittarius" to t(
            "You arrive open, candid and ready to go somewhere—someone who seeks meaning and possibility. People often find you refreshing and sometimes too blunt; your first reaction to a new situation is to look for what’s interesting or expansive. That brings enthusiasm and a broad view, but it can also read as restlessness or inconsistency. Aim to temper bluntness with attentive listening, follow through on promising leads and channel your curiosity into projects that sustain rather than scatter your energy.",
            "Пристигате отворени, откровени и готови за движение — образ на човек, който търси смисъл и възможности. Хората ви намират освежаващи и понякога прекалено директни; вашият първи импулс към нова ситуация е да потърсите интересното или широката перспектива. Това носи ентусиазъм и оптимизъм, но може да създаде впечатление на лекомислие или непостоянство. Практика е да балансирате спонтанността с последователност и да използвате откровеността за свързване, не за нараняване."
        ),
        "asc_capricorn" to t(
            "You come across as serious, reliable and often more composed than your years. People tend to hand you responsibility and trust your steadiness. That earns respect, yet it can make you appear distant or guarded emotionally. Themes include discipline, long-term planning and authority; a practical approach is to let a few humanizing details show, accept support when it’s offered, and schedule time for rest and lighter pursuits so responsibility doesn’t become burden.",
            "Излизате пред хората сериозни, отговорни и надеждни — понякога изглеждате по-възрастни или по-уравновесени, отколкото сте. Околните често ви дават отговорност без да попитат и разчитат на стабилността ви. Това ви дава уважение, но може да ви направи дистанционни или предпазливи към уязвимост. Темите включват дисциплина, дългосрочно планиране и авторитет; полезно е да показвате малки човешки страни, да приемате подкрепа и да отделяте време за почивка и игра."
        ),
        "asc_aquarius" to t(
            "You come across as your own person—slightly apart, hard to categorize and not doing things the usual way. That makes you memorable and often attracts curiosity about your unconventional views. First impressions of you can differ widely: some see a visionary, others find you detached or eccentric. Themes include individuality, innovation and social thinking; a helpful strategy is to find compatible circles, explain your choices with clarity when needed, and use your originality to collaborate rather than isolate.",
            "Хората ви възприемат като независими и различни — малко встрани от общото, трудни за поместване в стандартни кутии. Това ви прави запомнящи се и често привлича интерес към нестандартните ви възгледи. Първите впечатления от вас могат да варират значително в зависимост от наблюдателя: за някои сте визионер, за други — хладен или ексцентричен. Темите са индивидуалност, иновация и социални идеи; практическото предизвикателство е да намирате съмишленици и да обяснявате различията си така, че да изграждате реални връзки."
        ),
        "asc_pisces" to t(
            "You come across as soft-edged and receptive, and people often confide in you sooner than they expect. You tend to take on the tone of whoever you’re with, which makes you easy to be around but sometimes hard to pin down as an individual. Themes include empathy, intuition and creative sensitivity; consider practicing clearer boundaries and grounding techniques, channeling your receptivity into creative or compassionate work, and reserving time to replenish your own emotional reserves.",
            "Излизате пред хората с меки контури и висока възприемчивост — често хората ви споделят неща по-рано, отколкото са планирали. Склонни сте да отразявате настроението на обкръжението си, което ви прави лесни за общуване, но и трудни за уловими като индивидуалност. Темите включват емпатия, интуиция и творческа чувствителност; практическо насочване е да работите върху граници и заземяване, да канализирате чувствителността в изкуство или помощ на другите и да запазвате време за възстановяване."
        ),
    )
}
