package eu.kastroguru.astrodiary.domain.interpretation.written

import eu.kastroguru.astrodiary.domain.interpretation.Bilingual

/**
 * Hand-written Midheaven-in-sign texts: what a person becomes known for and which direction their
 * work pulls in. Completes the angle table together with [AscendantInSign].
 */
object MidheavenInSign {

    private fun t(en: String, bg: String) = Bilingual(en, bg)

    val entries: Map<String, Bilingual> = mapOf(
        "mc_aries" to t(
            "In public you’re often the one who goes first — quick to start, decisive and willing to take risks. Your career path can feel like a series of bold launches rather than a steady climb. That brings energy and visibility but also a tendency toward impulsive choices or burnout. It can help to channel your drive into short, focused projects, build routines for longer-term goals, and learn to share initiative with reliable partners so you don’t have to carry every risk alone.",
            "Пред света често сте онзи, който тръгва пръв — инициативен, бърз в решенията и склонен да поема риск. Кариерата ви може да наподобява серия от пробиви и нови старти, а не плавно изкачване. Това носи енергия и видимост, но и риск от импулсивни избори или изгаряне. Полезно е да канализирате огнения импулс в проекти с ясни, краткотрайни цели, да практикувате търпение при дългосрочни планове и да обмисляте колаборации, които смекчават нуждата да носите всичко сами."
        ),
        "mc_taurus" to t(
            "Your reputation tends to be built slowly and to endure — what you produce often stands the test of time. Careers involving steadiness, craftsmanship, money management or handling tangible resources suit you. Growth usually comes by accumulation rather than sudden leaps, which is stabilizing but can make you resistant to change. Practically, focus on creating reliable systems, investing in quality, and allowing occasional innovation so your slow growth doesn’t calcify into stagnation.",
            "Репутацията ви често се гради бавно, но остава устойчива — щом нещо е свършено от вас, то често издържа теста на времето. Подходящи са занимания, които изискват постоянство, материално изкуство, финансова отговорност или управление на ресурси. Пътят към признание може да изглежда бавен и натрупващ се; това е предимство, но също така може да води до съпротивление към промяна. Практически съвет: изграждайте здрави системи, инвестирайте в качество и приемайте периодични иновации, за да избегнете застой."
        ),
        "mc_gemini" to t(
            "Your public image often centers on words, connections and information flow. You may be known as a communicator, teacher, networker or someone juggling several roles rather than a single narrow title. Variety suits you, but there’s a risk of scattering focus or staying superficial. It’s useful to package your ideas into clear messages, commit to a few reliable collaborations, and balance breadth with occasional deep dives so your versatility translates into a coherent professional identity.",
            "Публичният ви образ често е свързан с думите, връзките и обмена на информация. Може да се отличавате като говорител, учител, медиатор или мултитаскинг професионалист, който управлява няколко проекта едновременно. Предпочитате разнообразие пред едно тясно определение на длъжността, но има риск да разпилеете енергия или да останете на повърхността на темите. Помага да структурирате идеите си в ясни послания, да избирате постоянни партньорства и да комбинирате ширина с дълбочина, когато е необходимо."
        ),
        "mc_cancer" to t(
            "Your public role often highlights caretaking and protection — even if your job title doesn’t say so, you tend to show empathy and personal investment. Careers involving homes, family, food, safety or social support suit you best. You’re most effective when you feel emotionally connected, but there’s a risk of carrying too much personal vulnerability into the public sphere. Establishing healthy boundaries and systems lets you sustain care over the long term without becoming depleted.",
            "Във видимата ви роля често изпъква грижата и защитата — дори ако титлата не казва „грижовен/а“, вашият подход е емпатичен и ангажиран. Подходящи са професии свързани с дом, семейство, храна, безопасност, социална подкрепа или емоционално обслужване. За да сте ефективни, често трябва да се чувствате лично вложени. Внимавайте обаче да не пренесете прекалено много лична уязвимост в публичната сфера; полезно е да създавате граници и устойчиви структури, които да подкрепят вашата емпатия без да изтощават."
        ),
        "mc_leo" to t(
            "Your public position often calls for visibility and creative leadership. Recognition tends to function as fuel — not mere vanity, but a resource that amplifies your work. Roles where your contribution is openly connected to your name suit you well. The downside can be seeking applause at the expense of substance or sidelining teamwork. Practically, hone your craft, distribute the spotlight when possible, and use visibility to inspire others as well as to validate yourself.",
            "Вашето публично място често изисква видимост и творческо лидерство. Признанието може да ви служи като гориво за по-добра работа — не просто като суета, а като ресурс, който подхранва вашия принос. Подходящи са роли, в които вашето име и принос са ясно свързани с резултата. Рискът е да търсите одобрение на всяка цена или да пренебрегнете екипната работа. Практически подход: развивайте уменията си, споделяйте вниманието и използвайте сцената за вдъхновение, а не само за потвърждение."
        ),
        "mc_virgo" to t(
            "Your standing often rests on professionalism, precision and attention to detail. You’re valued as the person who fixes errors, refines processes and brings systems to work. Careers needing expertise, analysis or service suit you well. There’s a tendency toward self-criticism or preferring to stay behind the scenes rather than seek the spotlight. It can help to make your methods visible, teach what you know, and let your competence become the public face of your work.",
            "Репутацията ви често се гради върху професионализъм, точност и внимание към детайла. Хората ви ценят като човек, който поправя грешките, усъвършенства процеси и внася системност. Подходящи са занимания, изискващи експертиза, анализ и служба. Съществува тенденция към прекомерна самокритика или да оставате зад кулисите, защото предпочитате да работите, а не да блестите. Практически съвет: показвайте системите и методите си, учете другите — това засилва общественото признание без да компрометира интегритета ви."
        ),
        "mc_libra" to t(
            "Your public role often runs through relationships: representing others, mediating, pairing things up and creating agreeable balance. You do well where taste, diplomacy and fairness matter. You may face the tension between wanting to be liked and needing to take a decisive stand, tending toward compromise. It helps to clarify your values and standards so you can assert yourself when required while still using your skill at connecting people and ideas.",
            "Публичният ви образ се оформя силно от начина, по който работите с хората — представяте идеи, посредничите и търсите справедливо решение. Това е видимо в професионални срещи, преговори и ситуации, в които трябва да балансирате различни интереси. Ще разпознаете трудността, когато желанието всички да ви харесват ви пречи да заемете ясна позиция. Конструктивният изход е да съчетаете дипломацията с ясни принципи и да казвате спокойно какво приемате и какво не."
        ),
        "mc_scorpio" to t(
            "You’re drawn to work with the hidden, the transformational and what others prefer not to discuss openly. Your reputation often carries intensity and gravity — you may be seen as resolute, probing, or depth-oriented. Authority can come through discretion, investigative or therapeutic roles, and the ability to face difficult truths without flinching. Be mindful of tendencies toward secrecy or manipulation; ethical transparency and safe channels for powerful work make your influence more sustainable and trustworthy.",
            "Привлича ви работа с подсъзнателното, трансформацията и онова, което другите избягват да обсъждат открито. Репутацията ви често носи интензитет и тежест — хората може да ви възприемат като сериозен, резолютен или търсещ дълбочина. Власт и влияние може да идват чрез дискретност, терапевтичен или изследователски подход и способността да стоите спокойно пред трудни истини. Внимавайте с тенденцията към манипулация или прекалено затвореност; етичната прозрачност и канали за безопасно споделяне правят силата по-устойчива."
        ),
        "mc_sagittarius" to t(
            "Your public persona often reflects a wider horizon: teaching, travel, publishing, philosophy or faith. You may be known as someone who frames the big picture and wants to share it — in media, education, international work or cultural exchange. Professionally you seek freedom and variety; a job stuck in one room or rigid routine will feel limiting. Watch for impatience with details and the tendency to overpromise; pairing expansive vision with concrete steps and steady follow-through helps turn ideals into reliable achievements.",
            "Публичният ви образ често се свързва с разширени хоризонти: преподаване, пътувания, издаване, философия или духовни убеждения. Може да ви познават като човек, който вижда голямата картина и иска да я сподели — в медии, образование, международни контакти или културни мостове. В професията търсите свобода и разнообразие; работа, ограничена до едно място или рутинна процедура, бързо ви задушава. Внимавайте с нетърпението към детайла и склонността да обещавате повече, отколкото можете да изпълните; практичен план и последователност ще ви помогнат да превърнете визията си в устойчив успех."
        ),
        "mc_capricorn" to t(
            "Your public standing is shaped by discipline, structure and a slow, steady climb. You often take responsibility early and build your position step by step; titles, standards and institutional respect matter. Recognition may arrive later but tends to be enduring. The tension can be excessive ambition, workaholism or putting career ahead of personal life; setting clear boundaries and finding meaning in the work itself — not just in external approval — helps sustain long-term success.",
            "Публичният ви образ е материализиран чрез дисциплина, структура и постепенен напредък. Често поемате отговорности рано и сте склонни да строите кариера стъпка по стъпка — титли, стандарти и институционална стабилност имат значение. Признанието може да дойде по-късно, но е по-трайно. Опасността е в изтощителната амбиция, прекалената сериозност или поставянето на работата пред личния живот; полезно е да установите граници и да намерите смисъл в това, което градите, а не само в общественото одобрение."
        ),
        "mc_aquarius" to t(
            "Your public identity often stands out for originality and an unconventional approach. Roles involving systems, technology, social networks, group work or reform suit you — precisely where the established method has stopped working, you can propose alternatives. You may be seen as an innovator or someone who introduces change. Tensions can include emotional detachment or unpredictability; channeling your independence into collective projects and communicating ideas clearly helps them gain traction and practical impact.",
            "Публичният ви стил често се отличава с оригиналност и нестандартен подход. Подходящи са ви роли, свързани със системи, технологии, социални мрежи, групова организация или реформа — там където установеният начин спира да работи, вие често предлагате алтернатива. Може да ви видят като иноватор или като човека, който въвежда промяна. Възможни напрежения включват емоционално дистанциране или непредсказуемост; ползотворно е да канализирате независимостта си в колективни проекти и да обсъждате идеите си, за да получат опора."
        ),
        "mc_pisces" to t(
            "Your public direction may be non‑linear and compassionate; forcing a rigid path rarely serves you well. Roles in the arts, caregiving, healing, or spiritual work fit — anything that requires imagination and empathy. Public roles can be subtle, transformative or behind-the-scenes, and you may need to deliberately build clear boundaries and professional frameworks. Risks include blurred identity, overgiving or lack of visibility; pairing sensitivity with practical routines and containers helps protect your energy and make your gifts sustainable.",
            "Публичната посока при вас може да бъде нелинейна и емпатична; принудително структуриране рядко дава добри резултати. Подходящи са ви изкуство, грижа, лечение, духовни практики и дейности, които изискват въображение и интуиция. Публичните роли могат да са нежни, скрити или трансформативни, и често изискват от вас да изградите съзнателно ясни граници и професионални рамки. Рискове са размиване на аза, прекомерно отдаване или неясна публична идентичност; полезно е да съчетаете чувствителността с устойчиви практики и структури, които защитават енергията ви."
        ),
    )
}
