package eu.kastroguru.astrodiary.domain.interpretation.written

import eu.kastroguru.astrodiary.domain.interpretation.Bilingual

/**
 * The second half of a chain reading: where the matter is actually decided, once per ruler house.
 *
 * Twelve lines that pair with any of the 156 planet-in-house lines, so the 1,872 readings are built
 * from written text rather than composed out of dictionary entries. Light and concrete on purpose —
 * this is the sentence that tells someone what to do about it.
 */
object RulerHouseKey {

    private fun t(en: String, bg: String) = Bilingual(en, bg)

    val byHouse: Map<Int, Bilingual> = mapOf(
        1 to t(
            "The focal point often lies in how you present yourself — posture, tone, visible choices. Shifting your self-presentation can change how situations unfold: adjust body language, communication style or decision-making habits and external circumstances may follow. Practical steps include experimenting with new roles, clarifying boundaries and rehearsing different ways of showing up. Expect friction from entrenched habits and from people used to the old version of you; take gradual steps, track small wins, and treat public behavior as a place for low-risk experiments that teach you what really sticks.",
            "Темата се проявява най-ясно в начина, по който действате и се представяте пред хората. Ще забележите това в първото впечатление, езика на тялото, стила на общуване и начина, по който взимате решения. Ако старото ви поведение вече не ви служи, околните може да реагират на промяната, преди самите вие да се почувствате уверени в нея. Конструктивният изход е да избирате по-ясно как искате да бъдете възприемани и да го показвате последователно, без да играете роля, която не ви е естествена."
        ),
        2 to t(
            "This point concerns material security and personal values — income, possessions and what you truly prioritize. Getting practical about resources and clarifying what you value often brings stability elsewhere. Useful steps include reviewing budgets, decluttering, exploring additional income streams and separating self-worth from belongings. Tensions can arise from fear of loss, attachment to comfort or impulsive spending. Address these by creating realistic plans, setting priorities and building small financial habits that boost confidence and reduce volatility without demanding dramatic, unsustainable changes.",
            "Темата се свързва с парите, притежанията и личните ви ценности. В ежедневието това може да се види в доходите, разходите, усещането ви за сигурност или в избора какво си струва да запазите. Ще разпознаете напрежението, когато страхът от недостиг ви кара да трупате, да харчите импулсивно или да мерите собствената си стойност с материални неща. Конструктивният изход е ясен бюджет, разумни приоритети и по-стабилно усещане за собствена стойност, което не зависи от притежанията."
        ),
        3 to t(
            "Outcomes are often decided in everyday communication — conversations, messages, short meetings and routine exchanges. What you say, how you listen and whether you follow through matter. Practical steps: state intentions clearly, keep brief notes of agreements, respond promptly and practice active listening. Risks include miscommunication, gossip or unspoken expectations. Small communication habits — tone, consistency and context — can shift results dramatically, so treat routine exchanges as meaningful and manageable opportunities to influence direction rather than trivial background noise.",
            "Темата се развива в разговорите и ежедневния обмен с хората около вас. Важни могат да се окажат съобщение, кратка среща, документ, обещание или начинът, по който сте разбрали чужди думи. Ще разпознаете трудността, когато недоизказаното, прибързаният отговор или различното тълкуване създадат проблем. Конструктивният изход е да казвате точно какво имате предвид, да проверявате договореното и да слушате внимателно, преди да действате."
        ),
        4 to t(
            "The core often sits in the home and family sphere — roots, need for security and long-term living conditions. Restabilizing things may require setting domestic boundaries, reorganizing your physical space or addressing inherited behavior patterns. Practical approaches include establishing routines that create a sense of safety, evaluating living arrangements and having family discussions aimed at mutual understanding. Challenges can come from avoiding family topics or triggering strong emotional responses; incremental changes to your environment and clearer household expectations can gradually shift the foundation you operate from.",
            "Темата се проявява най-силно у дома и в отношенията със семейството. Жилището, чувството за сигурност, семейните решения или стари модели на поведение могат да определят как се развива ситуацията. Ще разпознаете напрежението, когато премълчани семейни теми, липса на лични граници или неспокойна домашна среда започнат да влияят и на останалата част от живота ви. Конструктивният изход е по-спокойна домашна среда, ясни граници и разговори, в които всеки може да каже от какво има нужда."
        ),
        5 to t(
            "This moves through pleasure, creativity and the willingness to take risks — self-expression, romance, hobbies and play are central. When joy or the courage to try is absent, momentum often stalls. Practical measures include scheduling creative experiments, taking small calculated risks and allowing yourself low-stakes pleasures without demanding perfection. Tensions may involve fear of failure, a need for approval or excessive caution; approach change through incremental experiments, celebrate process over outcome and use playful practices to reopen channels of inspiration and attraction.",
            "Темата се развива чрез любовта, творчеството, удоволствието и смелостта да покажете нещо лично. Това може да се види в романтична връзка, хоби, личен проект, отношения с деца или желание да бъдете забелязани с това, което създавате. Ще разпознаете блокажа, когато страхът от провал или чуждото мнение ви кара да играете на сигурно и да не опитвате. Конструктивният изход е да си позволите експерименти, игра и малки рискове, без да изисквате от себе си съвършен резултат."
        ),
        6 to t(
            "This depends on daily habits, health and practical organization — body care, work duties and what you do each day. Improvements in routine can produce steady progress: optimize sleep, nutrition, task lists and tracking systems. Prioritize sustainable habits over sudden overhauls. Challenges include perfectionism or neglecting self-care; small consistent changes usually yield more than dramatic interventions. Treat the mundane as the engine of change and design simple rituals that support energy and focus rather than relying on occasional bursts of effort.",
            "Темата се проявява в ежедневната работа, навиците и грижата за тялото. Ще я забележите в начина, по който организирате задачите си, спите, почивате, храните се или поемате служебни ангажименти. Проблемът личи, когато хаотичният режим, претоварването или стремежът всичко да бъде идеално започнат да изчерпват силите ви. Конструктивният изход е проста и устойчива рутина, ясни приоритети, разумно разпределяне на задачите и достатъчно време за възстановяване."
        ),
        7 to t(
            "The process goes through another person or a partnership — personal relationships, business alliances or contractual arrangements may determine the outcome. You often cannot resolve this alone; dialogue, explicit agreements and sometimes compromise are required. Practical steps include open communication, formalizing expectations and checking reciprocity in contributions. Potential tensions include conflicts of interest, mirrored dynamics or imbalanced power; aim for negotiated boundaries, transparent terms and shared responsibility to move things forward collaboratively rather than through unilateral action.",
            "Важните събития по тази тема се случват чрез отношенията ви с друг човек. Партньор, клиент или открит опонент може да се окаже човекът, чрез когото ситуацията се развива. Ще разпознаете напрежението, когато решенията зависят от чуждата позиция, очакванията са неясни или единият човек дава повече от другия. Конструктивният изход е открит разговор, конкретни договорки и ясни граници, така че и двете страни да знаят какво поемат."
        ),
        8 to t(
            "This hinges on shared resources, intimate matters and what often remains unspoken — debts, inheritances, joint accounts and emotional entanglements. It also points to transformation, secrecy and deep personal change. Practical steps include frank conversations about financial obligations, reviewing paperwork, clarifying arrangements for shared funds and addressing trust dynamics in close relationships. Fears of loss, control or exploitation can surface; pursuing transparency, negotiated boundaries and fair allocation of responsibilities helps reduce risk and supports more conscious, regenerative change.",
            "Темата се проявява в общите пари, дълговете, наследствата, интимността и доверието между хората. Ситуацията може да стане особено видима при общ бюджет, кредит, наследствен въпрос или момент, в който трябва да споделите нещо много лично. Ще разпознаете трудността, когато страхът от загуба или нуждата от контрол пречат на открития разговор. Конструктивният изход е прозрачност за парите и отговорностите, ясни договорки и постепенно изграждане на доверие."
        ),
        9 to t(
            "With the ruler in the 9th house, resolutions often come by widening your perspective — through travel, higher learning, long-distance mentors, or exposure to other cultures and belief systems. This placement points to growth via philosophy, publishing, legal matters, or formal study. Staying within the same social circle tends to slow progress or keep things stuck. Practical steps include enrolling in a course, taking a trip that challenges your assumptions, seeking teachers outside your usual network, and reading diverse viewpoints. These actions can turn abstract ideas into meaningful forward motion.",
            "Темата се развива, когато излезете извън познатото — чрез пътуване, обучение, контакт с друга култура, важна правна тема или промяна във възгледите ви. Ще разпознаете това, когато старият начин на мислене вече не обяснява добре случващото се и търсите по-широка перспектива. Конструктивният изход е да учите от хора с различен опит, да проверявате убежденията си и да превръщате новото знание в реални решения."
        ),
        10 to t(
            "When the ruler sits in the 10th house, outcomes are filtered through career, public standing and the way others see you. Reputation, official roles and long-term vocational goals often determine how matters resolve — perception can outweigh private intention. This placement encourages attention to visible achievements, professional etiquette and relationships with authorities. Practical advice: clarify the image you want to project, deliver consistent results, and cultivate influential contacts while remaining true to your values. Managing how you’re perceived can open doors, but avoid sacrificing integrity for appearance.",
            "Темата се проявява в работата, кариерата и начина, по който ви виждат публично. Началник, професионална възможност, нова отговорност или промяна в репутацията ви може да се окаже решаваща за развитието на ситуацията. Ще разпознаете напрежението, когато личните ви намерения се разминават с професионалните очаквания или когато се опитвате да поддържате образ, който не ви подхожда. Конструктивният изход е да поемате видими отговорности, да показвате реални резултати и да изграждате професионална репутация, която съответства на ценностите ви."
        ),
        11 to t(
            "With the ruler in the 11th house, progress tends to come through networks: friends, communities and collaborators who share your hopes and goals often accelerate outcomes. Collective energy can provide resources, introductions and momentum that individual effort would take much longer to achieve. Tensions may arise if fitting in dilutes your unique voice or if group dynamics demand compromises. Practical steps: articulate shared aims before committing, choose alliances that respect your priorities, and balance collaborative projects with solo time to maintain clarity of purpose.",
            "Темата се развива чрез приятели, колеги, общности и хора, с които споделяте цели. Група, познанство или професионална мрежа може да ви даде информация, подкрепа или възможност, до която трудно бихте стигнали сами. Ще разпознаете напрежението, когато желанието да се впишете започне да измества собствените ви цели. Конструктивният изход е да избирате среда с близки ценности, да допринасяте ясно към общите цели и да запазвате място за собствените си идеи."
        ),
        12 to t(
            "When the ruler falls in the 12th house, matters tend to resolve quietly — through solitude, inner work, therapy, dream incubation or behind-the-scenes help rather than public action. Outcomes often ripen slowly as unconscious material surfaces and is integrated. This placement favors retreat, compassionate service, and confidential support, but it can also blur boundaries if you overgive. Practical guidance: carve out time for reflection, keep a dream or feelings journal, consult a trusted therapist or mentor, and allow patience; the solution often appears subtly rather than by force.",
            "Темата се развива в уединение, зад кулисите или в периоди, когато имате нужда да останете насаме със себе си. Сънища, терапия, духовни практики, тайни договорки или нерешени вътрешни въпроси могат да повлияят на ситуацията, без това да е видимо за околните. Ще разпознаете трудността, когато избягвате реалността, пазите твърде много неща за себе си или се изтощавате, опитвайки се да помагате на всички. Конструктивният изход е да си дадете време за тишина и възстановяване, да назовавате скритите проблеми и да търсите подкрепа, когато не можете да ги решите сами."
        ),
    )

    fun of(house: Int): Bilingual? = byHouse[house]
}
