package eu.kastroguru.astrodiary.domain.interpretation.written

import eu.kastroguru.astrodiary.domain.interpretation.Bilingual

/**
 * Hand-written Sun-in-sign texts — the placement a newcomer reads first, so it is written properly
 * rather than composed. Keys match NatalInterpretations: planet key + sign, lower case.
 */
object SunInSign {

    private fun t(en: String, bg: String) = Bilingual(en, bg)

    val entries: Map<String, Bilingual> = mapOf(
        "sun_aries" to t(
            "You feel alive when you’re the one who gets things started: initiative energizes you, and challenges wake your appetite for life. Waiting for permission can be draining, while doing and correcting in motion feels natural. You tend to favor action over prolonged deliberation, which can lead to impulsive choices and a pattern of many beginnings without enough follow-through. Useful approaches are deliberately choosing closure moments, channeling assertive energy into safe outlets, and practicing patience so your bold starts turn into sustainable achievement.",
            "Чувствате се живи, когато сте този, който започва: инициативата зарежда, конкуренцията и предизвикателствата събуждат енергия. Чакането за разрешение често ви изцежда, докато действието ви дава усещане за смисъл. Склонни сте да предпочетете действие и корекция на място пред дълги размишления, което може да доведе до импулсивни решения и незавършени проекти. Практическите стратегии включват съзнателно планиране на завършвания, търсене на безопасни канали за изява на агресията и работа върху търпението, за да умножите ползите от вашата инициатива."
        ),
        "sun_taurus" to t(
            "You become yourself through what you build and preserve — tangible outcomes give a sense of authenticity. You need to see real returns on effort: a home, a skill, financial stability. Your progress typically comes from steadiness rather than speed. When pressured to change before you’re ready, you may dig in; that persistence is both a strength and a barrier. Finding balance can mean cultivating flexibility practices that protect your foundations while allowing selective, purposeful change.",
            "Ставате себе си през това, което изграждате и съхранявате — стабилните резултати дават усещането за автентичност. Нуждаете се да видите материален отпечатък от усилията си: дом, умение, финансовата сигурност. Вашият напредък е по-скоро резултат от последователност, отколкото от бързина. Когато ви притискат да променяте посоката преди да сте готови, може да се вкопаете; тази устойчивост е едновременно ресурс и ограничаващ фактор. Балансът може да дойде от практики, които въвеждат гъвкавост без да жертвате корените си."
        ),
        "sun_gemini" to t(
            "You’re at your best when there’s something new to learn and someone to tell it to — curiosity is a way of being, not a pastime. You often form opinions aloud, testing ideas in conversation to see what holds. Mental agility and variety energize you, but they can also foster superficiality: many starts but few deep finishes. Practical strategies include scheduling focused blocks for sustained work and choosing pursuits that encourage depth as well as breadth.",
            "В най-добрата си форма сте, когато има какво ново да научите и комуникирате — любопитството е начин на живот, не просто хоби. Често оформяте мнение в разговора, като пробвате идеи гласно и виждате кои държат вода. Склонността към разнообразие и умствена подвижност ви носи оживление, но може да доведе до повърхностност: много начала, малко задълбочаване. Полезно е да структурирате периоди за фокус и да избирате проекти, които ви дават възможност да дълбаете, не само да започвате."
        ),
        "sun_cancer" to t(
            "You feel most yourself where there is safety — emotional, physical, or familial — and you often create that sense of security for others. You tend to pick up on the mood of a room and retain emotional impressions of people and places for a long time. When threatened, withdrawal can feel safer than direct confrontation, which others may misread as indifference; your impulse is usually protective rather than uncaring. Useful work includes setting boundaries that allow safety without isolation and finding conscious ways to express and share feelings.",
            "Себе си чувствате там, където има безопасност — емоционална, физическа или семейна — и често градите тази сигурност и за другите. Имате способността да усещате атмосферата и да помните емоционалните отпечатъци на хора и места с години напред. Когато се почувствате застрашени, предпочитате отдръпване пред директна конфронтация, което понякога се тълкува като дистанция; истинският ви стремеж обикновено е към защита и грижа. Работете върху граници, които позволяват безопасност без изолация, и намерете начини да изразявате емоциите си съзнателно."
        ),
        "sun_leo" to t(
            "You need your work and presence to be recognized — not applause for its own sake, but the sense that what you offer reaches someone. When this recognition is present, you tend to be generous, warm, and resilient; when it’s missing you may overperform or withdraw, and withdrawal often costs most. Core themes: creativity, leadership, self‑expression. Practical guidance: cultivate inner validation, share the spotlight deliberately, and build projects where your gifts are seen without making approval the only reward.",
            "Имате нужда усилието ви да бъде забелязано — не просто аплауз заради аплодисментите, а усещането, че дарът ви стига до друг човек. Когато това присъства, ставате щедър, топъл и устойчив пред неуспехите; когато липсва, може да се престараете или да се отдръпнете, а отдръпването често боли повече. Темите тук включват творчество, лидерство и самоутвърждаване. Практически: работете върху вътрешното признание и създавайте роли, в които вашият талант служи и се вижда, без да зависи изцяло от външна похвала."
        ),
        "sun_virgo" to t(
            "You come into your own by making things work — noticing the flaws others skip and taking satisfaction in fixing them. That same exacting eye often turns inward, so you can produce excellent work and still feel behind. Themes include service, attention to detail, and practicality; pitfalls are perfectionism and harsh self‑judgment. Useful practices: set compassionate standards, prioritize tasks that matter most, and allow delegation so your energy isn’t drained by minutiae.",
            "Влизате в своето, когато правите нещата да работят — виждате пропуска, който другите подминават, и поправянето му ви носи истинско удовлетворение. Същото критично око често се обръща и към вас, затова можете да постигате високо качество, но да се чувствате все още недоволни. Темите включват служене, детайлна преценка и ефективност; рисковете са перфекционизъм и прекомерна самокритика. Полезно е да развивате състрадание към собствените си граници, да приоритизирате и да делегирате, за да запазите ресурсите си."
        ),
        "sun_libra" to t(
            "You find yourself in relation to others — weighing how choices land on people often before you register your own preference, which makes you fair and pleasant company. That tendency can leave you unsure of what you truly want and hesitant to voice unpopular truths. Themes: balance, diplomacy, aesthetics. Constructive steps: clarify your priorities, practice saying difficult things with care, and set boundaries so your generosity doesn’t erase your identity.",
            "Откривате себе си в отношенията — мерите как дадено решение ще се отрази на другите почти преди собствените си предпочитания, което ви прави справедливи и приятни за компания. Но тази склонност може да донесе неяснота какво наистина искате и да ви затрудни да кажете непопулярното. Темите са баланс, дипломация и естетика; конструктивна работа включва да оформяте и отстоявате лични граници, да вземате решения с ясно чувство за приоритет и да практикувате честност, която съхранява връзките."
        ),
        "sun_scorpio" to t(
            "You don’t do things halfway. You want to know what’s really going on beneath the polite surface, keep your counsel, and attach deeply to a few rather than lightly to many. Loyalty runs as deep as suspicion; this gives you transformative power but also risks control and jealousy. Themes: intensity, regeneration, intimacy. Helpful practices: learn when to let go, channel passion into creative or healing work, and set clear emotional boundaries to protect both you and those you love.",
            "Не се занимавате с половин мерки. Искате да знаете какво стои под финото, пазите мислите си и привързвате дълбоко към малко хора вместо леко към мнозина. Верността ви е дълбока, както и вашето подозрение; във властта ви е както силата на трансформация, така и склонността към контрол или ревност. Темите са интензитет, възраждане и интимност. Полезно е да учите кога да пускате, да канализирате интензитета творчески и да търсите ясни граници между крайна подкрепа и задушаване."
        ),
        "sun_sagittarius" to t(
            "You need room and meaning — meaning often matters more than security, so you’ll trade comfort for a larger view: travel, study, and beliefs that broaden your horizon. Boxed in, you grow restless and blunt, and the honesty that serves you can become tactless. Themes: exploration, freedom, philosophy. Practical guidance: temper passion with patience, attend to useful details, and direct your appetite for growth into experiences that deepen rather than scatter your purpose.",
            "Нуждаете се от простор и от смисъл—за вас значението често тежи повече от сигурността, затова предпочитате по‑широка перспектива пред удобството: пътуване, учене, вярвания, които разширяват хоризонта. Затворени в тесни рамки, ставате неспокойни и грубовати, а честността ви може да загуби такт. Темите са търсене, свобода и идеали; полезно е да култивирате търпение към детайлите, да развивате дипломатичност и да насочвате стремежа към устойчиво разширяване на опита."
        ),
        "sun_capricorn" to t(
            "You’re built for the long game. You prefer to earn and preserve things over time, assume responsibility early, and are often the person others rely on. Your strengths are discipline and strategic planning; risks include equating worth with achievement and carrying too much. Practical steps: set clear priorities, learn to delegate, and schedule recovery so long‑term ambition doesn’t erode personal life and wellbeing.",
            "Съсредоточени сте върху дългосрочния напредък. Предпочитате да заслужите нещо бавно и да го запазите, поемате отговорност по-рано и често сте човекът, на когото другите разчитат. Силата ви е дисциплината и стратегическото планиране; рискът е да се мерите единствено с постиженията и да носите повече, отколкото признавате. Практично: задавайте ясни приоритети, учете се да делегирате и отделяйте време за възстановяване, така че устойчивата кариера да не изяде личния живот."
        ),
        "sun_aquarius" to t(
            "You need to think for yourself and tend to notice patterns rather than isolated facts. Being told what to believe often produces the opposite reflex, and you’re frequently the one asking why things are done this way at all. Distance gives clarity and originality but can keep others farther away than intended. Themes: individuality, community, ideals. Practice translating ideas into practical projects and cultivating closeness while preserving autonomy.",
            "Импулсът ви е към самостоятелно мислене и забелязване на модели, а не отделни случаи. Когато ви казват какво да вярвате, често изпитвате обратен рефлекс, и вие сте този, който пита „защо така въобще?“. Разстоянието ви дава яснота и оригиналност, но може да държи хората на разстояние. Темите са индивидуалност, общност и идеали; полезно е да учите как да превеждате идеите си в практични действия и да изграждате интимност без да губите независимостта си."
        ),
        "sun_pisces" to t(
            "You take in more than you can always explain: moods, music, and other people’s states reach you directly, making you compassionate and imaginative but also easily flooded. Your work is boundary‑setting — discerning which feelings in the room are truly yours and where your help stops being helpful. Practical suggestions: channel sensitivity into art or healing, establish grounding routines, and set clear limits so empathy remains sustainable.",
            "Поемате повече от обстоятелствата, отколкото можете лесно да обясните: настроения, музика, усещанията на другите стигат до вас директно. Това ви прави състрадателни и въображаеми, но и уязвими на „наводняване“ от чужди емоции. Работата ви включва граници, различаване кое чувство е ваше и къде помощта спира да бъде полезна. Практически: използвайте структурирани изразни форми — изкуство, ритуал, терапия — и създайте ежедневни практики за заземяване и възстановяване."
        ),
    )
}
